/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJodDetail.java
 *
 * Created on Feb 18, 2012, 9:05:03 AM
 */

package technician;

import accessory.ReceiveAccessoriesForJob;
import componentControl.AutoGenerate;
import control.JobDetailControl;
import control.ServiceOrderControl;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import model.*;

/**
 *
 * @author Amila Karunathilaka
 */
public class AddJodDetail extends javax.swing.JDialog {
    ServiceOrder serviceOrder;
    ServiceOrderDetail serviceOrderDetail;
    Map<String, Object> modelList;
    ArrayList<AccessoriesDetail> accessoriesDetailList;
    ArrayList<EmployeeDetail> employeeDetailList;
    Map<String, Object> orderList;
    DefaultListModel<String> dlm;
    String Item_Code;
    /** Creates new form NewJodDetail */
    public AddJodDetail(java.awt.Frame parent, boolean modal,ServiceOrder serviceOrder,ServiceOrderDetail serviceOrderDetail) {
        super(parent, modal);
        initComponents();
        this.serviceOrder=serviceOrder;
        this.serviceOrderDetail=serviceOrderDetail;
        viewServiceOrder();
        dlm=new DefaultListModel<String>();
        txtJobCode.setText(AutoGenerate.getNextID("JobDetail", "Job_Code", "J"));
        accessoriesDetailList=new ArrayList<AccessoriesDetail>();
    }
  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lbJobCode = new javax.swing.JLabel();
        lbJobDeficiency = new javax.swing.JLabel();
        txtJobDeficiency = new javax.swing.JTextField();
        txtJobCode = new javax.swing.JTextField();
        lbAddJobDescription = new javax.swing.JLabel();
        txtAddJobDescription = new javax.swing.JTextField();
        btmoveJobDescription = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listJobDescription = new javax.swing.JList();
        btReceiveAccessories = new javax.swing.JButton();
        bEmployeeChargeDetail = new javax.swing.JButton();
        btStates1 = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        lbServiceOrderID = new javax.swing.JLabel();
        lbItemDescription = new javax.swing.JLabel();
        lbBrandName = new javax.swing.JLabel();
        txtBrandName = new javax.swing.JTextField();
        txtItemDescription = new javax.swing.JTextField();
        txtServiceOrderID = new javax.swing.JTextField();
        btaddJob = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("New Job  Detail"));

        lbJobCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbJobCode.setText("Job Code");
        lbJobCode.setBounds(20, 30, 110, 15);
        jLayeredPane2.add(lbJobCode, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbJobDeficiency.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbJobDeficiency.setText("Job Deficiency");
        lbJobDeficiency.setBounds(20, 70, 120, 15);
        jLayeredPane2.add(lbJobDeficiency, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtJobDeficiency.setBounds(150, 70, 430, 25);
        jLayeredPane2.add(txtJobDeficiency, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtJobCode.setEditable(false);
        txtJobCode.setBounds(150, 30, 160, 25);
        jLayeredPane2.add(txtJobCode, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbAddJobDescription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbAddJobDescription.setText("Add Job Description");
        lbAddJobDescription.setBounds(20, 130, 150, 15);
        jLayeredPane2.add(lbAddJobDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtAddJobDescription.setBounds(20, 160, 350, 25);
        jLayeredPane2.add(txtAddJobDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btmoveJobDescription.setText(">>");
        btmoveJobDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmoveJobDescriptionActionPerformed(evt);
            }
        });
        btmoveJobDescription.setBounds(410, 160, 50, 30);
        jLayeredPane2.add(btmoveJobDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        listJobDescription.setBorder(javax.swing.BorderFactory.createTitledBorder("Job Description"));
        jScrollPane1.setViewportView(listJobDescription);

        jScrollPane1.setBounds(500, 110, 400, 130);
        jLayeredPane2.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btReceiveAccessories.setText("Receive Accessories");
        btReceiveAccessories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReceiveAccessoriesActionPerformed(evt);
            }
        });
        btReceiveAccessories.setBounds(620, 270, 180, 30);
        jLayeredPane2.add(btReceiveAccessories, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bEmployeeChargeDetail.setText("Insert Job Team");
        bEmployeeChargeDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmployeeChargeDetailActionPerformed(evt);
            }
        });
        bEmployeeChargeDetail.setBounds(470, 270, 140, 30);
        jLayeredPane2.add(bEmployeeChargeDetail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btStates1.setText("States");
        btStates1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStates1ActionPerformed(evt);
            }
        });
        btStates1.setBounds(810, 270, 110, 30);
        jLayeredPane2.add(btStates1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(30, 190, 940, 330);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Service Order Detail"));

        lbServiceOrderID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbServiceOrderID.setText("Service Order ID");
        lbServiceOrderID.setBounds(20, 30, 110, 15);
        jLayeredPane3.add(lbServiceOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbItemDescription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbItemDescription.setText("Item Description");
        lbItemDescription.setBounds(20, 70, 120, 15);
        jLayeredPane3.add(lbItemDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbBrandName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbBrandName.setText("Brand Name");
        lbBrandName.setBounds(590, 70, 90, 15);
        jLayeredPane3.add(lbBrandName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtBrandName.setEditable(false);
        txtBrandName.setBounds(680, 70, 190, 25);
        jLayeredPane3.add(txtBrandName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtItemDescription.setEditable(false);
        txtItemDescription.setBounds(150, 70, 390, 25);
        jLayeredPane3.add(txtItemDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtServiceOrderID.setEditable(false);
        txtServiceOrderID.setBounds(150, 30, 160, 25);
        jLayeredPane3.add(txtServiceOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBounds(30, 80, 940, 110);
        jLayeredPane1.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btaddJob.setText("Submit Job");
        btaddJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddJobActionPerformed(evt);
            }
        });
        btaddJob.setBounds(850, 520, 130, 40);
        jLayeredPane1.add(btaddJob, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmoveJobDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmoveJobDescriptionActionPerformed
        dlm.addElement(txtAddJobDescription.getText());
        listJobDescription.setModel(dlm);
        txtAddJobDescription.setText("");
        txtAddJobDescription.requestFocus();
    }//GEN-LAST:event_btmoveJobDescriptionActionPerformed

    private void btReceiveAccessoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReceiveAccessoriesActionPerformed
        new ReceiveAccessoriesForJob(this, true,accessoriesDetailList).setVisible(true);
    }//GEN-LAST:event_btReceiveAccessoriesActionPerformed

    private void bEmployeeChargeDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmployeeChargeDetailActionPerformed
        
    }//GEN-LAST:event_bEmployeeChargeDetailActionPerformed

    private void btStates1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStates1ActionPerformed
        setDateTime();
    }//GEN-LAST:event_btStates1ActionPerformed

    private void btaddJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddJobActionPerformed
        addJobDetail();
        clear();
    }//GEN-LAST:event_btaddJobActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddJodDetail dialog = new AddJodDetail(new javax.swing.JFrame(), true,new ServiceOrder(),null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEmployeeChargeDetail;
    private javax.swing.JButton btReceiveAccessories;
    private javax.swing.JButton btStates1;
    private javax.swing.JButton btaddJob;
    private javax.swing.JButton btmoveJobDescription;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAddJobDescription;
    private javax.swing.JLabel lbBrandName;
    private javax.swing.JLabel lbItemDescription;
    private javax.swing.JLabel lbJobCode;
    private javax.swing.JLabel lbJobDeficiency;
    private javax.swing.JLabel lbServiceOrderID;
    private javax.swing.JList listJobDescription;
    private javax.swing.JTextField txtAddJobDescription;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtItemDescription;
    private javax.swing.JTextField txtJobCode;
    private javax.swing.JTextField txtJobDeficiency;
    private javax.swing.JTextField txtServiceOrderID;
    // End of variables declaration//GEN-END:variables
    private void viewServiceOrder(){
        try {
            modelList=ServiceOrderControl.viewServiceOrder(serviceOrder);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddCondition.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddCondition.class.getName()).log(Level.SEVERE, null, ex);
        }
        serviceOrder=(ServiceOrder)modelList.get("ServiceOrder");
        ServiceItem item=(ServiceItem)modelList.get("Item");
        txtServiceOrderID.setText(serviceOrder.getService_Order_ID());
        txtItemDescription.setText(item.getDescription());
        txtBrandName.setText(item.getItem_Brand_Name());
        Item_Code=item.getItem_Code();
    }
    private void addJobDetail(){
        JobDetail jobDetail=new JobDetail(txtJobCode.getText(), txtJobDeficiency.getText(),0.00,0.00,0.00 ,0.00, setDateTime(), null, 0,Item_Code,"A");
        ArrayList<JobDescription> jobDescriptionList=new ArrayList<JobDescription>();
        JobDescription jobDescription=null;
        for(int i=0;i<dlm.getSize();i++){
            jobDescription=new JobDescription(i+1, dlm.get(i), txtJobCode.getText());
            jobDescriptionList.add(jobDescription);
        }
        try {
            int res1=JobDetailControl.addJobDetail(jobDetail);
            int res2=JobDetailControl.addJobDecription(jobDescriptionList);
            if(res1==1&&res2==1){
                JOptionPane.showMessageDialog(this, "Job added", "Success", JOptionPane.OK_OPTION);
                if (!(serviceOrderDetail==null)) {
                    serviceOrderDetail.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                    this.dispose();
                }
            }else{
               JOptionPane.showMessageDialog(this, "Job Fail", "Fail", JOptionPane.OK_OPTION);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddJodDetail.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddJodDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(accessoriesDetailList!=null&& !accessoriesDetailList.isEmpty()){
            
        }
    }
    
    private String setDateTime(){
       SimpleDateFormat SDF=new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
       String Date=SDF.format(Calendar.getInstance().getTime());
       System.out.println(Date);
       return Date;
    }
    
    private void clear(){
        txtJobCode.setText(AutoGenerate.getNextID("JobDetail", "Job_Code", "J"));
        txtJobDeficiency.setText("");
        dlm.removeAllElements();
        listJobDescription.setModel(dlm);
    }
}
