/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package technician;

import accessory.ReceiveAccessoriesForJob;
import java.util.ArrayList;
import model.AccessoriesDetail;

/**
 *
 * @author Amila
 */
public class JobReceiveAccessoriesDetail extends javax.swing.JDialog {
    ArrayList<AccessoriesDetail> accessoriesDetailList;
    /**
     * Creates new form JobReceiveAccessoriesDetail
     */
    public JobReceiveAccessoriesDetail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAccessoriesDetail = new javax.swing.JTable();
        lbJobCode = new javax.swing.JLabel();
        txtJobCode = new javax.swing.JTextField();
        lbAccessoriesTotalAmount = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JTextField();
        btBack = new javax.swing.JButton();
        btReceiveAccessories = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbAccessoriesDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Accessory Code", "Accessory Description", "Unit Price", "Quantity", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbAccessoriesDetail);

        jScrollPane1.setBounds(20, 170, 960, 230);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbJobCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbJobCode.setText("Job Code");
        lbJobCode.setBounds(50, 100, 110, 17);
        jLayeredPane1.add(lbJobCode, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtJobCode.setEditable(false);
        txtJobCode.setBounds(170, 100, 170, 25);
        jLayeredPane1.add(txtJobCode, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbAccessoriesTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAccessoriesTotalAmount.setText("Total Amount");
        lbAccessoriesTotalAmount.setBounds(660, 430, 120, 17);
        jLayeredPane1.add(lbAccessoriesTotalAmount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtTotalAmount.setEditable(false);
        txtTotalAmount.setBounds(790, 430, 170, 25);
        jLayeredPane1.add(txtTotalAmount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btBack.setText("Back");
        btBack.setBounds(840, 520, 120, 30);
        jLayeredPane1.add(btBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btReceiveAccessories.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btReceiveAccessories.setText("Receive New Accessories");
        btReceiveAccessories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReceiveAccessoriesActionPerformed(evt);
            }
        });
        btReceiveAccessories.setBounds(590, 520, 220, 30);
        jLayeredPane1.add(btReceiveAccessories, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btReceiveAccessoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReceiveAccessoriesActionPerformed
        new ReceiveAccessoriesForJob(this, true, accessoriesDetailList).setVisible(true);
    }//GEN-LAST:event_btReceiveAccessoriesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JobReceiveAccessoriesDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JobReceiveAccessoriesDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JobReceiveAccessoriesDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JobReceiveAccessoriesDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JobReceiveAccessoriesDetail dialog = new JobReceiveAccessoriesDetail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btReceiveAccessories;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAccessoriesTotalAmount;
    private javax.swing.JLabel lbJobCode;
    private javax.swing.JTable tbAccessoriesDetail;
    private javax.swing.JTextField txtJobCode;
    private javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables
}
