/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package technician;

import componentControl.FillComboBox;
import control.JobDetailControl;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author Amila
 */
public class MyJobDetail extends javax.swing.JPanel {
    Map<String, Object> modelList;
    TechnicianMain technicianMain;
    ConfirmJobComplete confirmJobComplete;
    JPanel pan;
    DefaultTableModel dtm;
    ServiceItem item;
    /**
     * Creates new form MyJobDetail
     */
    public MyJobDetail(TechnicianMain technicianMain,JPanel pan) {
        initComponents();
        this.technicianMain=technicianMain;
        this.pan=pan;
        dtm=(DefaultTableModel)tbJobDetail.getModel();
        FillComboBox.fillComboDatabase(cmbServiceOrder, "ServiceOrder", "Service_Order_ID");
        checkbt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lbItemDescrription = new javax.swing.JLabel();
        txtItemDescription = new javax.swing.JTextField();
        lbServiceOrderID = new javax.swing.JLabel();
        cmbServiceOrder = new javax.swing.JComboBox();
        btSearch = new javax.swing.JButton();
        btAddNewJob = new javax.swing.JButton();
        lbItemBrandName = new javax.swing.JLabel();
        txtItemBrandName = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        lbDescription = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listDescription = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbJobDetail = new javax.swing.JTable();
        btConfirmSelectJobFinish = new javax.swing.JButton();
        btJobStates = new javax.swing.JButton();
        btback = new javax.swing.JButton();

        setOpaque(false);

        lbItemDescrription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbItemDescrription.setText("Item Descrription");
        lbItemDescrription.setBounds(20, 90, 130, 15);
        jLayeredPane2.add(lbItemDescrription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtItemDescription.setEditable(false);
        txtItemDescription.setBounds(170, 90, 420, 22);
        jLayeredPane2.add(txtItemDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbServiceOrderID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbServiceOrderID.setText("Service Order ID");
        lbServiceOrderID.setBounds(20, 10, 120, 15);
        jLayeredPane2.add(lbServiceOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cmbServiceOrder.setEditable(true);
        cmbServiceOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbServiceOrderKeyReleased(evt);
            }
        });
        cmbServiceOrder.setBounds(170, 10, 140, 22);
        jLayeredPane2.add(cmbServiceOrder, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btSearch.setText("Search");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });
        btSearch.setBounds(380, 10, 90, 23);
        jLayeredPane2.add(btSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btAddNewJob.setText("Add New Job");
        btAddNewJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddNewJobActionPerformed(evt);
            }
        });
        btAddNewJob.setBounds(730, 80, 150, 30);
        jLayeredPane2.add(btAddNewJob, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbItemBrandName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbItemBrandName.setText("Item Brand Name");
        lbItemBrandName.setBounds(20, 50, 130, 15);
        jLayeredPane2.add(lbItemBrandName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtItemBrandName.setEditable(false);
        txtItemBrandName.setBounds(170, 50, 230, 22);
        jLayeredPane2.add(txtItemBrandName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(20, 80, 890, 130);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbDescription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDescription.setText("Description");
        lbDescription.setBounds(40, 150, 90, 20);
        jLayeredPane3.add(lbDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane2.setViewportView(listDescription);

        jScrollPane2.setBounds(160, 150, 600, 90);
        jLayeredPane3.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tbJobDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job Code", "Job Deficiency", "Start Date ", "Finish Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbJobDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbJobDetailMouseClicked(evt);
            }
        });
        tbJobDetail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbJobDetailFocusGained(evt);
            }
        });
        tbJobDetail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbJobDetailKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tbJobDetail);
        tbJobDetail.getColumnModel().getColumn(0).setPreferredWidth(10);
        tbJobDetail.getColumnModel().getColumn(2).setPreferredWidth(10);
        tbJobDetail.getColumnModel().getColumn(3).setPreferredWidth(10);

        jScrollPane3.setBounds(12, 10, 950, 120);
        jLayeredPane3.add(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btConfirmSelectJobFinish.setText("Confirm Select Job Complete");
        btConfirmSelectJobFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmSelectJobFinishActionPerformed(evt);
            }
        });
        btConfirmSelectJobFinish.setBounds(640, 260, 200, 30);
        jLayeredPane3.add(btConfirmSelectJobFinish, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btJobStates.setText("Job States");
        btJobStates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJobStatesActionPerformed(evt);
            }
        });
        btJobStates.setBounds(850, 260, 110, 30);
        jLayeredPane3.add(btJobStates, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBounds(10, 220, 980, 300);
        jLayeredPane1.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btback.setText("Back");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });
        btback.setBounds(890, 530, 100, 30);
        jLayeredPane1.add(btback, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbJobDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbJobDetailMouseClicked
        viewJobDeficiency();
        checkbt();
    }//GEN-LAST:event_tbJobDetailMouseClicked

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        //pan.removeAll();
       // checkServiceOrder.setVisible(true);
       // pan.add(checkServiceOrder);
       // pan.revalidate();
       // pan.repaint();
    }//GEN-LAST:event_btbackActionPerformed

    private void cmbServiceOrderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbServiceOrderKeyReleased
        checkbt();
    }//GEN-LAST:event_cmbServiceOrderKeyReleased

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        clear();
        viewJobsForServiceOrder();
        checkbt();
    }//GEN-LAST:event_btSearchActionPerformed

    private void btJobStatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJobStatesActionPerformed
        item.setDescription(txtItemDescription.getText());
        item.setService_Order_ID(cmbServiceOrder.getSelectedItem()+"");
        new AddJobStates(technicianMain, true, item).setVisible(true);
    }//GEN-LAST:event_btJobStatesActionPerformed

    private void btConfirmSelectJobFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmSelectJobFinishActionPerformed
        JobDetail jobDetail=new JobDetail();
        jobDetail.setItem_Code(item.getItem_Code());
        jobDetail.setJob_Code(tbJobDetail.getValueAt(tbJobDetail.getSelectedRow(), 0)+"");
        jobDetail.setJob_Deficiency(tbJobDetail.getValueAt(tbJobDetail.getSelectedRow(), 1)+"");
        confirmJobComplete=new ConfirmJobComplete(technicianMain, true, jobDetail);
        confirmJobComplete.setVisible(true);
    }//GEN-LAST:event_btConfirmSelectJobFinishActionPerformed

    private void btAddNewJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddNewJobActionPerformed
        ServiceOrder serviceOrder=new ServiceOrder();
        serviceOrder.setService_Order_ID(cmbServiceOrder.getSelectedItem()+"");
        new AddJodDetail(technicianMain, true, serviceOrder, null).setVisible(true);
    }//GEN-LAST:event_btAddNewJobActionPerformed

    private void tbJobDetailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbJobDetailFocusGained
        checkbt();
    }//GEN-LAST:event_tbJobDetailFocusGained

    private void tbJobDetailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbJobDetailKeyReleased
        checkbt();
    }//GEN-LAST:event_tbJobDetailKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddNewJob;
    private javax.swing.JButton btConfirmSelectJobFinish;
    private javax.swing.JButton btJobStates;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btback;
    private javax.swing.JComboBox cmbServiceOrder;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbDescription;
    private javax.swing.JLabel lbItemBrandName;
    private javax.swing.JLabel lbItemDescrription;
    private javax.swing.JLabel lbServiceOrderID;
    private javax.swing.JList listDescription;
    private javax.swing.JTable tbJobDetail;
    private javax.swing.JTextField txtItemBrandName;
    private javax.swing.JTextField txtItemDescription;
    // End of variables declaration//GEN-END:variables
    private void viewJobsForServiceOrder() {
        try {
            ServiceOrder serviceOrder=new ServiceOrder();
            serviceOrder.setService_Order_ID(cmbServiceOrder.getSelectedItem()+"");
            modelList=JobDetailControl.viewJobDetail(serviceOrder);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MyJobDetail.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MyJobDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
        item=(ServiceItem) modelList.get("Item");
        txtItemDescription.setText(item.getDescription());
        txtItemBrandName.setText(item.getItem_Brand_Name());
        ArrayList<JobDetail> jobDetailList=(ArrayList<JobDetail>) modelList.get("JobDetail");
        for (JobDetail jobDetail : jobDetailList) {
            Object[] row={jobDetail.getJob_Code(),jobDetail.getJob_Deficiency(),jobDetail.getStart_Date(),jobDetail.getFinish_Date()};
            dtm.addRow(row);
        }
        tbJobDetail.requestFocus();
    }
    private void viewJobDeficiency(){
        ArrayList<JobDescription> jobDescriptionList=(ArrayList<JobDescription>) modelList.get("JobDescriptionList");
        DefaultListModel<String> dlm=new DefaultListModel<String>();
        for (JobDescription description : jobDescriptionList) {
            JobDescription jobDescription=new JobDescription(0, description.getJob_Description(), tbJobDetail.getValueAt(tbJobDetail.getSelectedRow(), 0)+"");
            if (description.equals(jobDescription)) {
                dlm.addElement(description.getJob_Description());
            }
        }
        listDescription.setModel(dlm);
    }
    private void comboControl(JComboBox controlcmb){
        JTextField txt = (JTextField) controlcmb.getEditor().getEditorComponent();
        txt.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    viewJobsForServiceOrder();
                }
                checkbt();
            }
        });
    }
    private void checkbt(){
        Integer selectrow=tbJobDetail.getSelectedRow();
        if (selectrow==-1 || tbJobDetail.getValueAt(tbJobDetail.getSelectedRow(), 3)!=null) {
            btConfirmSelectJobFinish.setEnabled(false);
            
        }else{
            btConfirmSelectJobFinish.setEnabled(true);
            
        }
        if(txtItemDescription.getText().trim().isEmpty()){
            btAddNewJob.setEnabled(false);
            btJobStates.setEnabled(false);
        }else{
            btAddNewJob.setEnabled(true);
            btJobStates.setEnabled(true);
        }
    }
    
    private void clear(){
        txtItemBrandName.setText("");
        txtItemDescription.setText("");
        int rowcount=tbJobDetail.getRowCount();
        for (int i = 0; i < rowcount; i++) {
            dtm.removeRow(0);
        }
    }
   
}
