/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cashier;

import componentControl.AutoGenerate;
import componentControl.TextControl;
import componentControl.ValidationValues;
import connection.DBConn;
import connection.DBHandle;
import control.SalesItemControl;
import control.SalesOrderControl;
import dataFilesControl.FileUtil;
import glasspaneloader.ConfirmGlassPaneLoader;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import login.LoginMain;
import model.*;
import protections.Protector;

/**
 *
 * @author Amila
 */
public class BillCancel extends javax.swing.JPanel {

    CashierMain cashierMain;
    InternalFrame internalFrame;
    JPanel pan;
    DefaultTableModel dtm;
    ArrayList<String> orderIDList;
    ArrayList<SoldItem> soldItemList;
    ArrayList<SalesItem> salesItemList;
    SalesOrder salesOrder;
    int count;

    /**
     * Creates new form BillCancel
     */
    public BillCancel(CashierMain cashierMain, InternalFrame internalFrame, JPanel pan) {
        initComponents();
        this.cashierMain = cashierMain;
        this.internalFrame = internalFrame;
        this.pan = pan;
        dtm = (DefaultTableModel) tbSalesItem.getModel();
        internalFrame.setGlassPane(glassPaneLoader1);
        btCancelSalesOrder.setEnabled(false);
        internalFrame.getFocusOwner();
        txtSalesOrderID.requestFocus();
        System.out.println(glassPaneLoader1.getParent().getName() + " ssssssssss");

        /*
         * try { orderIDList=SalesOrderControl.getSalesOrderIDList(); } catch
         * (ClassNotFoundException ex) {
         * Logger.getLogger(BillCancel.class.getName()).log(Level.SEVERE, null,
         * ex); } catch (SQLException ex) {
         * Logger.getLogger(BillCancel.class.getName()).log(Level.SEVERE, null,
         * ex);
        }
         */
        orderIDList = new ArrayList<String>();
        orderIDList.add("OD0001");
        orderIDList.add("OD0002");
        orderIDList.add("OD0003");
        orderIDList.add("OD0004");
        orderIDList.add("OD0300");
        orderIDList.add("OD0025");

        TextControl.setdropdownlist(cashierMain, orderIDList, txtSalesOrderID);
        System.out.println(cashierMain.panelPane.getX() + "  " + cashierMain.panelPane.getX());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glassPaneLoader1 = new glasspaneloader.GlassPaneLoader();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtconfirmUserName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtconfirmPassword = new javax.swing.JPasswordField();
        btConfirm = new javax.swing.JButton();
        btcancel = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        lbServiceOrderID = new javax.swing.JLabel();
        txtSalesOrderID = new javax.swing.JTextField();
        lbDate = new javax.swing.JLabel();
        cmbcalOrderDate = new org.freixas.jcalendar.JCalendarCombo();
        jSeparator1 = new javax.swing.JSeparator();
        lbCustomerName = new javax.swing.JLabel();
        lbCustAddress = new javax.swing.JLabel();
        txtCustAddress = new javax.swing.JTextField();
        txtCustName = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        lbContactNo = new javax.swing.JLabel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSalesItem = new javax.swing.JTable();
        lbCustAddress2 = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JTextField();
        btCancelSalesOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        glassPaneLoader1.setPreferredSize(new java.awt.Dimension(1100, 650));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Do you want to change configuration setting ?");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("please confrm it.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("User Name");

        txtconfirmUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfirmUserNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Password");

        btConfirm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btConfirm.setText("Confirm");
        btConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmActionPerformed(evt);
            }
        });

        btcancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btcancel.setText("Cancel");
        btcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout glassPaneLoader1Layout = new javax.swing.GroupLayout(glassPaneLoader1);
        glassPaneLoader1.setLayout(glassPaneLoader1Layout);
        glassPaneLoader1Layout.setHorizontalGroup(
            glassPaneLoader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(glassPaneLoader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(glassPaneLoader1Layout.createSequentialGroup()
                    .addGap(0, 295, Short.MAX_VALUE)
                    .addGroup(glassPaneLoader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(glassPaneLoader1Layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(jLabel2))
                        .addGroup(glassPaneLoader1Layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jLabel3))
                        .addGroup(glassPaneLoader1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(txtconfirmUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(glassPaneLoader1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(txtconfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(glassPaneLoader1Layout.createSequentialGroup()
                            .addGap(260, 260, 260)
                            .addComponent(btConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 295, Short.MAX_VALUE)))
        );
        glassPaneLoader1Layout.setVerticalGroup(
            glassPaneLoader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(glassPaneLoader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(glassPaneLoader1Layout.createSequentialGroup()
                    .addGap(0, 203, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)
                    .addGroup(glassPaneLoader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(glassPaneLoader1Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtconfirmUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)
                    .addGroup(glassPaneLoader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(glassPaneLoader1Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtconfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(55, 55, 55)
                    .addGroup(glassPaneLoader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 204, Short.MAX_VALUE)))
        );

        jLayeredPane3.setBounds(30, 280, 0, 0);
        jLayeredPane1.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Order Detail"));

        lbServiceOrderID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbServiceOrderID.setText("Order ID");
        lbServiceOrderID.setBounds(40, 20, 160, 20);
        jLayeredPane4.add(lbServiceOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtSalesOrderID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSalesOrderID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSalesOrderIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalesOrderIDKeyTyped(evt);
            }
        });
        txtSalesOrderID.setBounds(150, 20, 170, 30);
        jLayeredPane4.add(txtSalesOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDate.setText("Date");
        lbDate.setBounds(560, 20, 70, 20);
        jLayeredPane4.add(lbDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cmbcalOrderDate.setEnabled(false);
        cmbcalOrderDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcalOrderDateActionPerformed(evt);
            }
        });
        cmbcalOrderDate.setBounds(620, 20, 250, 30);
        jLayeredPane4.add(cmbcalOrderDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 2));
        jSeparator1.setBounds(40, 60, 630, 2);
        jLayeredPane4.add(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbCustomerName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCustomerName.setText("Customer Name");
        lbCustomerName.setBounds(20, 80, 130, 20);
        jLayeredPane4.add(lbCustomerName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbCustAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCustAddress.setText("Customer Address");
        lbCustAddress.setBounds(20, 120, 140, 20);
        jLayeredPane4.add(lbCustAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtCustAddress.setEditable(false);
        txtCustAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustAddressActionPerformed(evt);
            }
        });
        txtCustAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustAddressKeyReleased(evt);
            }
        });
        txtCustAddress.setBounds(150, 120, 630, 30);
        jLayeredPane4.add(txtCustAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtCustName.setEditable(false);
        txtCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustNameActionPerformed(evt);
            }
        });
        txtCustName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustNameKeyReleased(evt);
            }
        });
        txtCustName.setBounds(150, 80, 380, 30);
        jLayeredPane4.add(txtCustName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtContactNo.setEditable(false);
        txtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNoActionPerformed(evt);
            }
        });
        txtContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContactNoKeyReleased(evt);
            }
        });
        txtContactNo.setBounds(650, 80, 230, 30);
        jLayeredPane4.add(txtContactNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbContactNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbContactNo.setText("Contact No");
        lbContactNo.setBounds(560, 80, 100, 20);
        jLayeredPane4.add(lbContactNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.setBounds(10, 70, 1080, 180);
        jLayeredPane1.add(jLayeredPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setBounds(700, 10, 290, 60);
        jLayeredPane1.add(jLayeredPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setMinimumSize(new java.awt.Dimension(960, 400));
        jLayeredPane2.setPreferredSize(new java.awt.Dimension(960, 500));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tbSalesItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model No", "Serial No", "Description", "Qty", "Unit Price", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbSalesItem);
        tbSalesItem.getColumnModel().getColumn(0).setPreferredWidth(150);
        tbSalesItem.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbSalesItem.getColumnModel().getColumn(2).setPreferredWidth(300);
        tbSalesItem.getColumnModel().getColumn(3).setPreferredWidth(50);
        tbSalesItem.getColumnModel().getColumn(4).setPreferredWidth(100);
        tbSalesItem.getColumnModel().getColumn(5).setPreferredWidth(100);

        jScrollPane1.setBounds(20, 10, 1040, 210);
        jLayeredPane2.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbCustAddress2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbCustAddress2.setText("Total Amount");
        lbCustAddress2.setBounds(740, 270, 140, 20);
        jLayeredPane2.add(lbCustAddress2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtTotalAmount.setEditable(false);
        txtTotalAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalAmount.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtTotalAmountPropertyChange(evt);
            }
        });
        txtTotalAmount.setBounds(870, 270, 190, 30);
        jLayeredPane2.add(txtTotalAmount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btCancelSalesOrder.setText("Submit");
        btCancelSalesOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelSalesOrderActionPerformed(evt);
            }
        });
        btCancelSalesOrder.setBounds(960, 310, 110, 30);
        jLayeredPane2.add(btCancelSalesOrder, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(10, 290, 1080, 350);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 32)); // NOI18N
        jLabel1.setText("Sales Invoice Cancel");
        jLabel1.setBounds(60, 10, 320, 50);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalAmountPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtTotalAmountPropertyChange
        // ValidationValues.ValidateCurrency(txtTotalAmount);
    }//GEN-LAST:event_txtTotalAmountPropertyChange

    private void btCancelSalesOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelSalesOrderActionPerformed
        count = 0;
        internalFrame.getGlassPane().setVisible(true);
    }//GEN-LAST:event_btCancelSalesOrderActionPerformed

    private void txtCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustNameActionPerformed

    private void txtCustNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustNameKeyReleased
    }//GEN-LAST:event_txtCustNameKeyReleased

    private void txtCustAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustAddressActionPerformed

    private void txtCustAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustAddressKeyReleased
    }//GEN-LAST:event_txtCustAddressKeyReleased

    private void txtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNoActionPerformed

    private void txtContactNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNoKeyReleased
    }//GEN-LAST:event_txtContactNoKeyReleased

    private void txtSalesOrderIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalesOrderIDKeyTyped
    }//GEN-LAST:event_txtSalesOrderIDKeyTyped

    private void txtSalesOrderIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalesOrderIDKeyReleased
        ValidationValues.ValidateSingleKoto(txtSalesOrderID);
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btCancelSalesOrder.setEnabled(true);
            getSalesOrderDetail(txtSalesOrderID.getText());
           // btCancelSalesOrder.setEnabled(true);
        }
    }//GEN-LAST:event_txtSalesOrderIDKeyReleased

    private void cmbcalOrderDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcalOrderDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcalOrderDateActionPerformed

    private void txtconfirmUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfirmUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmUserNameActionPerformed

    private void btConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmActionPerformed
        count++;
        if (checkPasswordwithUserName(txtconfirmUserName.getText(), new String(txtconfirmPassword.getPassword()))) {
        } else {
            JOptionPane.showMessageDialog(pan, "Your Password is no Correct...", "Incorrect", JOptionPane.ERROR_MESSAGE);
            if (count == 3) {
                internalFrame.getGlassPane().setVisible(false);
                JOptionPane.showMessageDialog(pan, "Sales Order is Cancelling Fail", "Fail", JOptionPane.ERROR_MESSAGE);
            }
            txtconfirmUserName.setText("");
            txtconfirmPassword.setText("");
        }
    }//GEN-LAST:event_btConfirmActionPerformed

    private void btcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelActionPerformed
        System.out.println(glassPaneLoader1.getParent().getName() + " ssssssssss");
        internalFrame.getGlassPane().setVisible(false);
        txtconfirmUserName.setText("");
        txtconfirmPassword.setText("");
    }//GEN-LAST:event_btcancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelSalesOrder;
    private javax.swing.JButton btConfirm;
    private javax.swing.JButton btcancel;
    private org.freixas.jcalendar.JCalendarCombo cmbcalOrderDate;
    private glasspaneloader.GlassPaneLoader glassPaneLoader1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbContactNo;
    private javax.swing.JLabel lbCustAddress;
    private javax.swing.JLabel lbCustAddress2;
    private javax.swing.JLabel lbCustomerName;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbServiceOrderID;
    private javax.swing.JTable tbSalesItem;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtCustAddress;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtSalesOrderID;
    private javax.swing.JTextField txtTotalAmount;
    private javax.swing.JPasswordField txtconfirmPassword;
    private javax.swing.JTextField txtconfirmUserName;
    // End of variables declaration//GEN-END:variables

    private void getSalesOrderDetail(String orderID) {
        Map<String, Object> modelList = null;
        salesItemList = new ArrayList<SalesItem>();
        double totalAmount = 0.00;
        try {
            salesOrder = SalesOrderControl.getSalesOrder(orderID);
            modelList = SalesOrderControl.getSalesOrderDetail(salesOrder);
            Customer customer = (Customer) modelList.get("Customer");
            soldItemList = (ArrayList<SoldItem>) modelList.get("SoldItemList");
            txtCustName.setText(customer.getCustName());
            txtCustAddress.setText(customer.getCustAddress());
            txtContactNo.setText(customer.getContactNo());
            cmbcalOrderDate.setDate(Date.valueOf(salesOrder.getOrder_Date()));
            for (SoldItem soldItem : soldItemList) {
                SalesItem salesItem = SalesItemControl.getSalesItem(soldItem.getModel_No(), "Model_No");
                salesItem.setItem_Qty(salesItem.getItem_Qty() + soldItem.getItem_Qty());
                salesItemList.add(salesItem);
                Object[] obj = {soldItem.getModel_No(), soldItem.getSerial_No(), soldItem.getItem_Description(), soldItem.getItem_Qty(), soldItem.getIssue_price(), soldItem.getAmount()};
                dtm.addRow(obj);
                totalAmount += soldItem.getAmount();
            }
            txtTotalAmount.setText(totalAmount + "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BillCancel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BillCancel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void cancelBill(String employeeID) {
        ArrayList<ReturnItem> returnItemList = new ArrayList<ReturnItem>();
        String transactionID = AutoGenerate.getNextID("Transaction", "", "TR");
        Transaction transaction = new Transaction(transactionID, setDateTime(Calendar.getInstance().getTime()), TransactionType.GOODISSUECANCEL.getCode());
        SalesOrderCancel salesOrderCancel = new SalesOrderCancel(txtSalesOrderID.getText(), setDateTime(Calendar.getInstance().getTime()), salesOrder.getTotal_Amount(), salesOrder.getDiscount(), transactionID, employeeID);
        ReturnItem returnItem;
        for (SoldItem soldItem : soldItemList) {
            returnItem = new ReturnItem(soldItem.getSerial_No(), soldItem.getModel_No(), soldItem.getItem_Description(), soldItem.getItem_Brand_Name(), soldItem.getReceive_price(), soldItem.getIssue_price(), soldItem.getItem_Qty(), soldItem.getAmount(), soldItem.getWarranty_Period(), soldItem.getOrder_ID());
            returnItemList.add(returnItem);
        }

    }

    private boolean checkPasswordwithUserName(String userName, String password) {
        boolean returnValue = false;
        String[] developerAccount = new String[2];
        try {
            FileUtil fileUtil = new FileUtil();
            developerAccount = fileUtil.readDeveloperAccount();
        } catch (IOException ex) {
            Logger.getLogger(BillCancel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(BillCancel.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (developerAccount[0].equals(userName) && developerAccount[1].equals(password)) {
            returnValue = true;
        } else {
            try {
                String query = "select * from SystemUser where User_Name='" + userName + "'";
                ResultSet rst = DBHandle.getData(DBConn.getConnectionToDB(), query);
                if (rst.next()) {
                    String user = rst.getString("User_Name");
                    String pass = rst.getString("Password");
                    System.out.println(user + " " + pass);
                    String d = "";
                    d = Protector.decrypt(pass, user, 5);
                    System.out.println(d);
                    if (userName.equals(user) && password.equals(d)) {
                        returnValue = true;
                    } else {
                        returnValue = false;
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(BillCancel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return returnValue;
    }

    private String setDateTime(java.util.Date date) {
        SimpleDateFormat SDF = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        String Date = SDF.format(date);
        System.out.println(Date);
        return Date;
    }
    
}
