/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cashier;

import componentControl.ValidationValues;

/**
 *
 * @author Amila
 */
public class InstallmentPayment extends javax.swing.JPanel {

    /**
     * Creates new form InstallmentPayment
     */
    public InstallmentPayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane3 = new javax.swing.JLayeredPane();
        lbServiceOrderID = new javax.swing.JLabel();
        txtSalesOrderID = new javax.swing.JTextField();
        lbDate = new javax.swing.JLabel();
        cmbcalOrderDate = new org.freixas.jcalendar.JCalendarCombo();
        AgreementID = new javax.swing.JLabel();
        txtAgreementID = new javax.swing.JTextField();
        lbTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lbCustName = new javax.swing.JLabel();
        txtCustName = new javax.swing.JTextField();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        lbServiceOrderID1 = new javax.swing.JLabel();
        txtSalesOrderID1 = new javax.swing.JTextField();
        lbDate1 = new javax.swing.JLabel();
        cmbcalOrderDate1 = new org.freixas.jcalendar.JCalendarCombo();
        AgreementID1 = new javax.swing.JLabel();
        txtAgreementID1 = new javax.swing.JTextField();
        lbTotal1 = new javax.swing.JLabel();
        txtTotal1 = new javax.swing.JTextField();
        lbCustName1 = new javax.swing.JLabel();
        txtCustName1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Basic Detail"));

        lbServiceOrderID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbServiceOrderID.setText("Order ID");
        lbServiceOrderID.setBounds(40, 30, 160, 20);
        jLayeredPane3.add(lbServiceOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtSalesOrderID.setEditable(false);
        txtSalesOrderID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSalesOrderID.setOpaque(false);
        txtSalesOrderID.setBounds(150, 30, 160, 25);
        jLayeredPane3.add(txtSalesOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDate.setText("Date");
        lbDate.setBounds(610, 30, 70, 20);
        jLayeredPane3.add(lbDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cmbcalOrderDate.setEnabled(false);
        cmbcalOrderDate.setBounds(690, 30, 240, 30);
        jLayeredPane3.add(cmbcalOrderDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        AgreementID.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AgreementID.setText("Agreement ID");
        AgreementID.setBounds(30, 140, 120, 20);
        jLayeredPane3.add(AgreementID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtAgreementID.setEditable(false);
        txtAgreementID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAgreementID.setBounds(150, 140, 160, 20);
        jLayeredPane3.add(txtAgreementID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTotal.setText("Total Amount");
        lbTotal.setBounds(610, 80, 120, 20);
        jLayeredPane3.add(lbTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtTotalPropertyChange(evt);
            }
        });
        txtTotal.setBounds(740, 80, 190, 23);
        jLayeredPane3.add(txtTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbCustName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCustName.setText("Customer Name");
        lbCustName.setBounds(20, 80, 120, 20);
        jLayeredPane3.add(lbCustName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtCustName.setEditable(false);
        txtCustName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCustName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtCustNamePropertyChange(evt);
            }
        });
        txtCustName.setBounds(150, 80, 360, 20);
        jLayeredPane3.add(txtCustName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1060, 200));

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Basic Detail"));

        lbServiceOrderID1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbServiceOrderID1.setText("Due Pay Amount");
        lbServiceOrderID1.setBounds(50, 40, 160, 17);
        jLayeredPane4.add(lbServiceOrderID1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtSalesOrderID1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSalesOrderID1.setBounds(250, 40, 210, 25);
        jLayeredPane4.add(txtSalesOrderID1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbDate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDate1.setText("Date");
        lbDate1.setBounds(610, 30, 70, 20);
        jLayeredPane4.add(lbDate1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cmbcalOrderDate1.setEnabled(false);
        cmbcalOrderDate1.setBounds(690, 30, 240, 30);
        jLayeredPane4.add(cmbcalOrderDate1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        AgreementID1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AgreementID1.setText("Payment Period");
        AgreementID1.setBounds(50, 160, 150, 20);
        jLayeredPane4.add(AgreementID1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtAgreementID1.setEditable(false);
        txtAgreementID1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAgreementID1.setBounds(620, 130, 160, 20);
        jLayeredPane4.add(txtAgreementID1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbTotal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTotal1.setText("Installment Amount");
        lbTotal1.setBounds(50, 100, 160, 20);
        jLayeredPane4.add(lbTotal1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtTotal1.setEditable(false);
        txtTotal1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotal1.setBounds(250, 100, 210, 23);
        jLayeredPane4.add(txtTotal1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbCustName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCustName1.setText("Customer Name");
        lbCustName1.setBounds(370, 270, 120, 20);
        jLayeredPane4.add(lbCustName1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtCustName1.setEditable(false);
        txtCustName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCustName1.setBounds(550, 270, 360, 20);
        jLayeredPane4.add(txtCustName1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBounds(250, 160, 180, 30);
        jLayeredPane4.add(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jLayeredPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 1060, 310));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtTotalPropertyChange
        ValidationValues.ValidateCurrency(txtTotal);
    }//GEN-LAST:event_txtTotalPropertyChange

    private void txtCustNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtCustNamePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustNamePropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgreementID;
    private javax.swing.JLabel AgreementID1;
    private org.freixas.jcalendar.JCalendarCombo cmbcalOrderDate;
    private org.freixas.jcalendar.JCalendarCombo cmbcalOrderDate1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLabel lbCustName;
    private javax.swing.JLabel lbCustName1;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbDate1;
    private javax.swing.JLabel lbServiceOrderID;
    private javax.swing.JLabel lbServiceOrderID1;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTotal1;
    private javax.swing.JTextField txtAgreementID;
    private javax.swing.JTextField txtAgreementID1;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtCustName1;
    private javax.swing.JTextField txtSalesOrderID;
    private javax.swing.JTextField txtSalesOrderID1;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotal1;
    // End of variables declaration//GEN-END:variables
}
