/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cashier;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import transparentBackground.TransferenceThisWindow;

/**
 *
 * @author Amila
 */
public class InternalFrame extends javax.swing.JInternalFrame {
    CashierMain cashierMain;
    Bill bill;
    BillCancel billCancel;
    AddServiceOrder addServiceOrder;

    /**
     * Creates new form InternalFrame
     */
    public InternalFrame() {
        initComponents();
        bill = new Bill(this, pan);
        pan.removeAll();
        bill.setVisible(true);
        pan.add(bill);
        pan.revalidate();
    }

    public InternalFrame(CashierMain cashierMain, JDesktopPane containPane, String name) {
        initComponents();
        this.cashierMain=cashierMain;
        if (name.equals("Bill")) {
            setTittle("Sales Invoice");
            bill = new Bill(cashierMain, this, pan);
            pan.removeAll();
            bill.setVisible(true);
            pan.add(bill);
            pan.revalidate();
        }else if (name.equals("AddServiceOrder")) {
            setTittle("New Service Order");
            addServiceOrder = new AddServiceOrder(cashierMain, pan);
            pan.removeAll();
            addServiceOrder.setVisible(true);
            pan.add(addServiceOrder);
            pan.revalidate();
        }else if (name.equals("cancel")){
            setTittle("New Service Order");
            billCancel = new BillCancel(cashierMain, this, pan);
            pan.removeAll();
            billCancel.setVisible(true);
            pan.add(billCancel);
            pan.revalidate();
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeiconified(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pan.setOpaque(false);
        pan.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        System.out.println(cashierMain.billInternalFrameList.size());
        cashierMain.billInternalFrameList.remove(InternalFrame.this);
        System.out.println(cashierMain.billInternalFrameList.size());
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeiconified

    }//GEN-LAST:event_formInternalFrameDeiconified

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pan;
    // End of variables declaration//GEN-END:variables
private void setTittle(String name){
    final String title = name;
    setFrameIcon(new ImageIcon(getClass().getResource("/pictures/Neotech.png")));
        new Thread() {

            public void run() {
                boolean check = true;
                while (true) {
                    for (int i = 0; i < title.length() + 1; i++) {
                        setTitle(title.substring(0, i));
                        try {
                            Thread.sleep(150);
                        } catch (Exception e) {
                        }
                    }
                    try {
                        Thread.sleep(800);
                    } catch (Exception e) {
                    }
                }
            }
        }.start();
}

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final InternalFrame other = (InternalFrame) obj;
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        return hash;
    }


}
