/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cashier;

import componentControl.AutoGenerate;
import componentControl.ValidationValues;
import control.SalesOrderControl;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.*;
import printreport.ReportControl;

/**
 *
 * @author Amila
 */
public class Payment extends javax.swing.JPanel {

    Map<String, Object> orderList;
    SalesOrder salesOrder;
    Customer customer;
    ArrayList<SoldItem> soldItemList;
    ArrayList<SalesItem> salesItemList;
    CashierMain cashierMain;
    JPanel pan;
    Bill bill;

    /**
     * Creates new form Payment1
     */
    public Payment(CashierMain cashierMain, JPanel pan, Map<String, Object> orderList, Bill bill) {
        initComponents();
        this.cashierMain = cashierMain;
        this.pan = pan;
        this.bill = bill;
        this.orderList = orderList;
        salesOrder = (SalesOrder) orderList.get("SalesOrder");
        customer = (Customer) orderList.get("Customer");
        soldItemList = (ArrayList<SoldItem>) orderList.get("SoldItemList");
        salesItemList = (ArrayList<SalesItem>) orderList.get("SalesItemList");
        setClear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        lbServiceOrderID = new javax.swing.JLabel();
        txtSalesOrderID = new javax.swing.JTextField();
        lbDate = new javax.swing.JLabel();
        cmbcalOrderDate = new org.freixas.jcalendar.JCalendarCombo();
        lbPaymentID = new javax.swing.JLabel();
        txtPaymentID = new javax.swing.JTextField();
        lbTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lbTotal1 = new javax.swing.JLabel();
        txtDisc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ratiobtCash = new javax.swing.JRadioButton();
        ratiobtCredit = new javax.swing.JRadioButton();
        lbTotal2 = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JTextField();
        paneCash = new javax.swing.JLayeredPane();
        lbCustomerName1 = new javax.swing.JLabel();
        txtCustName1 = new javax.swing.JTextField();
        lbAmount1 = new javax.swing.JLabel();
        txtAmount1 = new javax.swing.JTextField();
        lbCash = new javax.swing.JLabel();
        txtCash = new javax.swing.JTextField();
        lbBalance = new javax.swing.JLabel();
        btCashPay = new javax.swing.JButton();
        txtBalance = new javax.swing.JTextField();
        paneCredit = new javax.swing.JLayeredPane();
        lbCustomerName = new javax.swing.JLabel();
        txtCustName = new javax.swing.JTextField();
        lbAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lbBankName = new javax.swing.JLabel();
        txtBankName = new javax.swing.JTextField();
        lbChequeDate = new javax.swing.JLabel();
        lbIssueDate = new javax.swing.JLabel();
        lbBankBranch = new javax.swing.JLabel();
        txtBankBranch = new javax.swing.JTextField();
        lbBankCode = new javax.swing.JLabel();
        txtBankCode = new javax.swing.JTextField();
        lbChequeNo = new javax.swing.JLabel();
        txtChequeNo = new javax.swing.JTextField();
        comboIssuedate = new datechooser.beans.DateChooserCombo();
        comboChequedate = new datechooser.beans.DateChooserCombo();
        btCreditPay = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setOpaque(false);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Basic Detail"));

        lbServiceOrderID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbServiceOrderID.setText("Order ID");
        lbServiceOrderID.setBounds(40, 30, 160, 20);
        jLayeredPane3.add(lbServiceOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtSalesOrderID.setEditable(false);
        txtSalesOrderID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSalesOrderID.setOpaque(false);
        txtSalesOrderID.setBounds(150, 30, 160, 25);
        jLayeredPane3.add(txtSalesOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDate.setText("Date");
        lbDate.setBounds(490, 30, 70, 20);
        jLayeredPane3.add(lbDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cmbcalOrderDate.setEnabled(false);
        cmbcalOrderDate.setBounds(570, 30, 240, 30);
        jLayeredPane3.add(cmbcalOrderDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbPaymentID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPaymentID.setText("Payment ID");
        lbPaymentID.setBounds(40, 80, 100, 15);
        jLayeredPane3.add(lbPaymentID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtPaymentID.setEditable(false);
        txtPaymentID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPaymentID.setBounds(150, 80, 140, 20);
        jLayeredPane3.add(txtPaymentID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTotal.setText("Total");
        lbTotal.setBounds(480, 90, 100, 15);
        jLayeredPane3.add(lbTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTotal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtTotalPropertyChange(evt);
            }
        });
        txtTotal.setBounds(590, 90, 140, 20);
        jLayeredPane3.add(txtTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbTotal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTotal1.setText("Discount");
        lbTotal1.setBounds(480, 120, 100, 15);
        jLayeredPane3.add(lbTotal1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtDisc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDisc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscKeyReleased(evt);
            }
        });
        txtDisc.setBounds(590, 120, 70, 20);
        jLayeredPane3.add(txtDisc, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("%");
        jLabel1.setBounds(670, 120, 20, 20);
        jLayeredPane3.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Payment Option");
        jLabel2.setBounds(40, 110, 110, 20);
        jLayeredPane3.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(ratiobtCash);
        ratiobtCash.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ratiobtCash.setText("Cash");
        ratiobtCash.setOpaque(false);
        ratiobtCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratiobtCashActionPerformed(evt);
            }
        });
        ratiobtCash.setBounds(160, 110, 80, 23);
        jLayeredPane3.add(ratiobtCash, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(ratiobtCredit);
        ratiobtCredit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ratiobtCredit.setText("Credit");
        ratiobtCredit.setOpaque(false);
        ratiobtCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratiobtCreditActionPerformed(evt);
            }
        });
        ratiobtCredit.setBounds(160, 130, 93, 23);
        jLayeredPane3.add(ratiobtCredit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbTotal2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbTotal2.setText("Amount");
        lbTotal2.setBounds(480, 160, 100, 20);
        jLayeredPane3.add(lbTotal2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtTotalAmount.setEditable(false);
        txtTotalAmount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTotalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAmountActionPerformed(evt);
            }
        });
        txtTotalAmount.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtTotalAmountPropertyChange(evt);
            }
        });
        txtTotalAmount.setBounds(590, 160, 140, 21);
        jLayeredPane3.add(txtTotalAmount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBounds(20, 50, 1060, 200);
        jLayeredPane1.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneCash.setBorder(javax.swing.BorderFactory.createTitledBorder("Cash Detail"));

        lbCustomerName1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCustomerName1.setText("Customer Name");
        lbCustomerName1.setBounds(60, 50, 130, 20);
        paneCash.add(lbCustomerName1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtCustName1.setEditable(false);
        txtCustName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustName1ActionPerformed(evt);
            }
        });
        txtCustName1.setBounds(190, 50, 410, 30);
        paneCash.add(txtCustName1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbAmount1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbAmount1.setText("Amount");
        lbAmount1.setBounds(60, 100, 130, 20);
        paneCash.add(lbAmount1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtAmount1.setEditable(false);
        txtAmount1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtAmount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmount1ActionPerformed(evt);
            }
        });
        txtAmount1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtAmount1PropertyChange(evt);
            }
        });
        txtAmount1.setBounds(190, 100, 170, 30);
        paneCash.add(txtAmount1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbCash.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbCash.setText("Cash");
        lbCash.setBounds(60, 150, 130, 20);
        paneCash.add(lbCash, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtCash.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCashActionPerformed(evt);
            }
        });
        txtCash.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCashFocusLost(evt);
            }
        });
        txtCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCashKeyReleased(evt);
            }
        });
        txtCash.setBounds(190, 150, 170, 30);
        paneCash.add(txtCash, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbBalance.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbBalance.setText("Balance");
        lbBalance.setBounds(60, 210, 130, 20);
        paneCash.add(lbBalance, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btCashPay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCashPay.setText("Pay");
        btCashPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCashPayActionPerformed(evt);
            }
        });
        btCashPay.setBounds(960, 280, 90, 30);
        paneCash.add(btCashPay, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtBalance.setEditable(false);
        txtBalance.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBalanceActionPerformed(evt);
            }
        });
        txtBalance.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtBalancePropertyChange(evt);
            }
        });
        txtBalance.setBounds(190, 210, 170, 30);
        paneCash.add(txtBalance, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneCash.setBounds(20, 260, 1060, 320);
        jLayeredPane1.add(paneCash, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneCredit.setBorder(javax.swing.BorderFactory.createTitledBorder("Credit Detail"));

        lbCustomerName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCustomerName.setText("Customer Name");
        lbCustomerName.setBounds(40, 40, 130, 20);
        paneCredit.add(lbCustomerName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtCustName.setEditable(false);
        txtCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustNameActionPerformed(evt);
            }
        });
        txtCustName.setBounds(170, 40, 380, 30);
        paneCredit.add(txtCustName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbAmount.setText("Amount");
        lbAmount.setBounds(40, 80, 130, 20);
        paneCredit.add(lbAmount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtAmount.setEditable(false);
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        txtAmount.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtAmountPropertyChange(evt);
            }
        });
        txtAmount.setBounds(170, 80, 150, 30);
        paneCredit.add(txtAmount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbBankName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbBankName.setText("Bank Name");
        lbBankName.setBounds(40, 150, 130, 20);
        paneCredit.add(lbBankName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankNameActionPerformed(evt);
            }
        });
        txtBankName.setBounds(170, 150, 210, 30);
        paneCredit.add(txtBankName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbChequeDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbChequeDate.setText("Cheque Date");
        lbChequeDate.setBounds(40, 270, 130, 20);
        paneCredit.add(lbChequeDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbIssueDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIssueDate.setText("Issue Date");
        lbIssueDate.setBounds(410, 270, 130, 20);
        paneCredit.add(lbIssueDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbBankBranch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbBankBranch.setText("Bank Branch");
        lbBankBranch.setBounds(420, 150, 110, 20);
        paneCredit.add(lbBankBranch, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtBankBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankBranchActionPerformed(evt);
            }
        });
        txtBankBranch.setBounds(510, 150, 210, 30);
        paneCredit.add(txtBankBranch, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbBankCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbBankCode.setText("Bank Code");
        lbBankCode.setBounds(40, 190, 130, 20);
        paneCredit.add(lbBankCode, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtBankCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankCodeActionPerformed(evt);
            }
        });
        txtBankCode.setBounds(170, 190, 210, 30);
        paneCredit.add(txtBankCode, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbChequeNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbChequeNo.setText("Cheque No");
        lbChequeNo.setBounds(40, 230, 130, 20);
        paneCredit.add(lbChequeNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtChequeNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChequeNoActionPerformed(evt);
            }
        });
        txtChequeNo.setBounds(170, 230, 210, 30);
        paneCredit.add(txtChequeNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        comboIssuedate.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 12));
        comboIssuedate.setBounds(510, 270, 180, 20);
        paneCredit.add(comboIssuedate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        comboChequedate.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 12));
        comboChequedate.setBounds(170, 270, 180, 20);
        paneCredit.add(comboChequedate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btCreditPay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCreditPay.setText("Pay");
        btCreditPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreditPayActionPerformed(evt);
            }
        });
        btCreditPay.setBounds(960, 280, 90, 30);
        paneCredit.add(btCreditPay, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneCredit.setBounds(20, 260, 1060, 320);
        jLayeredPane1.add(paneCredit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        btBack.setBounds(953, 603, 110, 30);
        jLayeredPane1.add(btBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 32)); // NOI18N
        jLabel3.setText("Payment");
        jLabel3.setBounds(60, 0, 250, 50);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ratiobtCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratiobtCashActionPerformed
        select();
    }//GEN-LAST:event_ratiobtCashActionPerformed

    private void ratiobtCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratiobtCreditActionPerformed
        select();
    }//GEN-LAST:event_ratiobtCreditActionPerformed

    private void txtTotalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalAmountActionPerformed

    private void txtCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustNameActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankNameActionPerformed

    private void txtBankBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankBranchActionPerformed

    private void txtBankCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankCodeActionPerformed

    private void txtChequeNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChequeNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChequeNoActionPerformed

    private void txtCustName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustName1ActionPerformed

    private void txtAmount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmount1ActionPerformed

    private void txtCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCashActionPerformed

    private void txtBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        this.setVisible(false);
        pan.removeAll();
        bill.setVisible(true);
        pan.add(bill);
        pan.revalidate();
    }//GEN-LAST:event_btBackActionPerformed

    private void btCashPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCashPayActionPerformed
        addDB("Cash");
        bill.clear();
        this.setVisible(false);
        pan.removeAll();
        bill.setVisible(true);
        pan.add(bill);
        pan.revalidate();
    }//GEN-LAST:event_btCashPayActionPerformed

    private void btCreditPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreditPayActionPerformed
        addDB("Credit");
        setprint("Credit");
        bill.clear();
        this.setVisible(false);
        pan.removeAll();
        bill.setVisible(true);
        pan.add(bill);
        pan.revalidate();
    }//GEN-LAST:event_btCreditPayActionPerformed

    private void txtTotalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtTotalPropertyChange
        ValidationValues.ValidateCurrency(txtTotal);
    }//GEN-LAST:event_txtTotalPropertyChange

    private void txtTotalAmountPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtTotalAmountPropertyChange
        ValidationValues.ValidateCurrency(txtTotalAmount);
    }//GEN-LAST:event_txtTotalAmountPropertyChange

    private void txtAmount1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtAmount1PropertyChange
        ValidationValues.ValidateCurrency(txtTotalAmount);
    }//GEN-LAST:event_txtAmount1PropertyChange

    private void txtBalancePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtBalancePropertyChange
        ValidationValues.ValidateCurrency(txtTotalAmount);
        
    }//GEN-LAST:event_txtBalancePropertyChange

    private void txtCashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashKeyReleased
        ValidationValues.ValidateDoubleValues(txtCash);
        double value=Double.parseDouble(txtCash.getText())-Double.parseDouble(txtAmount1.getText());
        txtBalance.setText(value+"");
    }//GEN-LAST:event_txtCashKeyReleased

    private void txtCashFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCashFocusLost
        ValidationValues.ValidateCurrency(txtCash);
        
    }//GEN-LAST:event_txtCashFocusLost

    private void txtDiscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscKeyReleased
        ValidationValues.ValidateDoubleValues(txtDisc);

    }//GEN-LAST:event_txtDiscKeyReleased

    private void txtAmountPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtAmountPropertyChange
        ValidationValues.ValidateCurrency(txtCash);
    }//GEN-LAST:event_txtAmountPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btCashPay;
    private javax.swing.JButton btCreditPay;
    private javax.swing.ButtonGroup buttonGroup1;
    private org.freixas.jcalendar.JCalendarCombo cmbcalOrderDate;
    private datechooser.beans.DateChooserCombo comboChequedate;
    private datechooser.beans.DateChooserCombo comboIssuedate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLabel lbAmount;
    private javax.swing.JLabel lbAmount1;
    private javax.swing.JLabel lbBalance;
    private javax.swing.JLabel lbBankBranch;
    private javax.swing.JLabel lbBankCode;
    private javax.swing.JLabel lbBankName;
    private javax.swing.JLabel lbCash;
    private javax.swing.JLabel lbChequeDate;
    private javax.swing.JLabel lbChequeNo;
    private javax.swing.JLabel lbCustomerName;
    private javax.swing.JLabel lbCustomerName1;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbIssueDate;
    private javax.swing.JLabel lbPaymentID;
    private javax.swing.JLabel lbServiceOrderID;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTotal1;
    private javax.swing.JLabel lbTotal2;
    private javax.swing.JLayeredPane paneCash;
    private javax.swing.JLayeredPane paneCredit;
    private javax.swing.JRadioButton ratiobtCash;
    private javax.swing.JRadioButton ratiobtCredit;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtAmount1;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBankBranch;
    private javax.swing.JTextField txtBankCode;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtChequeNo;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtCustName1;
    private javax.swing.JTextField txtDisc;
    private javax.swing.JTextField txtPaymentID;
    private javax.swing.JTextField txtSalesOrderID;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables

    private void select() {
        if (ratiobtCash.isSelected()) {
            paneCredit.setVisible(false);
            paneCash.setVisible(true);
        } else if (ratiobtCredit.isSelected()) {
            paneCash.setVisible(false);
            paneCredit.setVisible(true);
        }
    }

    private void setprint(String term) {
        Map<String, Object> param = new HashMap<String, Object>();
        param.put("custname", customer.getCustName());
        param.put("custaddress", customer.getCustAddress());
        param.put("invoiceno", salesOrder.getOrder_ID());
        param.put("date", setDateTime());
        param.put("term", term);
        param.put("totalamount", ValidationValues.ValidateCurrencyValue(salesOrder.getTotal_Amount()+""));
        param.put("rep", cashierMain.getUserName());
        ReportControl.printBill(soldItemList, param);
    }

    private void setClear() {
        ratiobtCash.setSelected(true);
        paneCredit.setVisible(false);
        paneCash.setVisible(true);
        SalesOrder salesOrder = (SalesOrder) orderList.get("SalesOrder");
        Customer customer = (Customer) orderList.get("Customer");
        System.out.println(salesOrder.getTotal_Amount() + "");
        txtSalesOrderID.setText(salesOrder.getOrder_ID());
        txtTotal.setText(salesOrder.getTotal_Amount() + "");
        txtTotalAmount.setText(salesOrder.getTotal_Amount() + "");
        txtAmount.setText(salesOrder.getTotal_Amount() + "");
        txtAmount1.setText(salesOrder.getTotal_Amount() + "");
        txtCustName.setText(customer.getCustName());
        txtCustName1.setText(customer.getCustName());
        txtCash.setText("0.00");
        txtDisc.setText("0");
        txtPaymentID.setText(AutoGenerate.getNextID("SalesOrderPayment", "OrderPayment_ID", "PI"));
    }

    private void addDB(String term) {
        String transactionID=AutoGenerate.getNextID("Transaction", "", "TR");
        Transaction transaction=new Transaction(transactionID, setDateTime(), TransactionType.GOODISSUE.getCode());
        salesOrder.setTransaction_ID(transactionID);
        SalesOrderPayment salesOrderPayment = new SalesOrderPayment(txtPaymentID.getText(), Double.parseDouble(txtTotalAmount.getText()), setDateTime(), 0, txtSalesOrderID.getText());
        try {
            setprint(term);
            int res = SalesOrderControl.addSalesOrder(transaction,customer, salesOrder, soldItemList, salesItemList);
            int res2 = SalesOrderControl.addPayment(salesOrderPayment);
                if (res == 1 && res2 == 1) {
                    setprint(term);
                    JOptionPane.showMessageDialog(pan, "Sales Order added", "Success", JOptionPane.INFORMATION_MESSAGE);            
                } else {
                    JOptionPane.showMessageDialog(pan, "Sales Order Fail", "Fail", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    

    private String setDateTime() {
        SimpleDateFormat SDF = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        String Date = SDF.format(cmbcalOrderDate.getDate());
        System.out.println(Date);
        return Date;
    }
}
