/*
 *  BACA DENGAN TELITI !!!
 * 
 *  Anda boleh menggunakan, mengubah, menghapus, menambah, dan
 *  melakukan hal yang anda inginkan ke dalam source code ini.
 * 
 *  Dan saya tidak bertanggung jawab atas kesalahan,
 *  bug, atau keanehan yang ada dalam source code ini, dan
 *  saya juga TIDAK MENERIMA PERTANYAAN dari Anda
 *  mengenai isi source code ini.
 * 
 *  Semoga source code ini bermanfaat bagi Anda, dan juga
 *  bermanfaat bagi project yang sedang Anda buat.
 * 
 *  Salam saya, Eko Kurniawan Khannedy
 */

/*
 * GlassPaneLoading.java
 *
 * Created on 04 Feb 09, 13:31:41
 */
package glasspaneloader;

import java.awt.*;
import java.awt.event.*;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author echo
 */
public class GlassPaneLoader extends javax.swing.JPanel {

    private Color colorTranparan;

    /**
     * Creates new form GlassPaneLoading
     */
    public GlassPaneLoader() {
        colorTranparan = new Color(255, 255, 255, 175);
        initComponents();

        addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
            }
        });
        addMouseMotionListener(new MouseAdapter() {
        });
        addMouseWheelListener(new MouseAdapter() {
        });
        addKeyListener(new KeyAdapter() {
        });
    }

    @Override
    protected void paintComponent(Graphics g) {

        Graphics2D gd = (Graphics2D) g.create();

        gd.setColor(colorTranparan);
        gd.fillRect(0, 0, getWidth(), getHeight());

        gd.dispose();

        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);
        setPreferredSize(new Dimension(600, 240));
        setLayout(new AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
