/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package serviceOrder;

import control.ServiceOrderControl;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.ServiceItem;
import model.ServiceOrder;

/**
 *
 * @author Amila
 */
public class AllJobsFinishedServiceOrders extends javax.swing.JPanel {
    Map<String, Object> modelList;
    ServiceOrderMain serviceOrderMain;
    JPanel pan;
    DefaultTableModel dtm;
    ConfirmCompleteServiceOrder confirmCompleteServiceOrder ;
    /**
     * Creates new form AllJobsFinishedServiceOrders
     */
    public AllJobsFinishedServiceOrders(ServiceOrderMain serviceOrderMain,JPanel pan) {
        initComponents();
        this.serviceOrderMain=serviceOrderMain;
        this.pan=pan;
        dtm=(DefaultTableModel) tbJobsFinishServiceOrder.getModel();
        setTable();
        checkbt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbJobsFinishServiceOrder = new javax.swing.JTable();
        btViewSelectServiceOrder = new javax.swing.JButton();

        tbJobsFinishServiceOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service Order ID", "Item Brand Name", "Item Description", "Service Order Receive Date"
            }
        ));
        tbJobsFinishServiceOrder.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbJobsFinishServiceOrderFocusGained(evt);
            }
        });
        tbJobsFinishServiceOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbJobsFinishServiceOrderKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbJobsFinishServiceOrder);

        jScrollPane1.setBounds(30, 90, 940, 380);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btViewSelectServiceOrder.setText("Service Order Completed Confirm");
        btViewSelectServiceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewSelectServiceOrderActionPerformed(evt);
            }
        });
        btViewSelectServiceOrder.setBounds(743, 510, 200, 40);
        jLayeredPane1.add(btViewSelectServiceOrder, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbJobsFinishServiceOrderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbJobsFinishServiceOrderFocusGained
        checkbt();
    }//GEN-LAST:event_tbJobsFinishServiceOrderFocusGained

    private void tbJobsFinishServiceOrderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbJobsFinishServiceOrderKeyReleased
        checkbt();
    }//GEN-LAST:event_tbJobsFinishServiceOrderKeyReleased

    private void btViewSelectServiceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewSelectServiceOrderActionPerformed
        ServiceOrder serviceOrder=new ServiceOrder();
        serviceOrder.setService_Order_ID(tbJobsFinishServiceOrder.getValueAt(tbJobsFinishServiceOrder.getSelectedRow(), 0)+"");
        confirmCompleteServiceOrder = new ConfirmCompleteServiceOrder(null, true, serviceOrder,serviceOrderMain);
        confirmCompleteServiceOrder.setVisible(true);
    }//GEN-LAST:event_btViewSelectServiceOrderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btViewSelectServiceOrder;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbJobsFinishServiceOrder;
    // End of variables declaration//GEN-END:variables
    private void setTable(){
        try {
            modelList=ServiceOrderControl.allJobsFinishServiceOrders();
            System.out.println(modelList);
        } catch (SQLException ex) {
            Logger.getLogger(AllJobsFinishedServiceOrders.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AllJobsFinishedServiceOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("1");
        ArrayList<ServiceOrder> serviceorderList=(ArrayList<ServiceOrder>) modelList.get("ServiceOrderList");
        System.out.println("1");
        ArrayList<ServiceItem> itemList=(ArrayList<ServiceItem>) modelList.get("ItemList");
        System.out.println(serviceorderList.size());
        ServiceOrder serviceOrder=null;
        ServiceItem item=null;
        for (int i=0;i<serviceorderList.size();i++) {
            serviceOrder=serviceorderList.get(i);
            item=itemList.get(i);
            System.out.println(serviceOrder.getService_Order_ID()+item.getItem_Brand_Name()+item.getDescription()+serviceOrder.getOrder_Date());
            Object[] row={serviceOrder.getService_Order_ID(),item.getItem_Brand_Name(),item.getDescription(),serviceOrder.getOrder_Date()};
            dtm.addRow(row);
        }
    }
    
    private void checkbt(){
        Integer selectrow=tbJobsFinishServiceOrder.getSelectedRow();
        if (selectrow==-1) {
            btViewSelectServiceOrder.setEnabled(false);
        }else{
            btViewSelectServiceOrder.setEnabled(true);
        }
    }
}
