/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CheckServiceOrder.java
 *
 * Created on Feb 9, 2012, 6:58:35 PM
 */

package serviceOrder;

import cashier.*;
import componentControl.FillComboBox;
import control.JobDetailControl;
import control.ServiceOrderControl;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.Condition;
import model.Customer;
import model.ServiceItem;
import model.JobDetail;
import model.ServiceOrder;

/**
 *
 * @author Amila Karunathilaka
 */
public class CheckServiceOrder extends javax.swing.JPanel {
    Map<String, Object> modelList;
    ServiceOrderMain serviceOrderMain;
    JPanel pan;
    String Item_Code;
    /** Creates new form CheckServiceOrder */
    public CheckServiceOrder(ServiceOrderMain serviceOrderMain,JPanel pan) {
        initComponents();
        this.serviceOrderMain=serviceOrderMain;
        this.pan=pan;
        FillComboBox.fillComboDatabase(cmbServiceOrder, "ServiceOrder", "Service_Order_ID");
        comboControl(cmbServiceOrder);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        btSearch = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lbCustName = new javax.swing.JLabel();
        lbCustAddress = new javax.swing.JLabel();
        lbContactNo = new javax.swing.JLabel();
        txtCustName = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        txtCustAddress = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        lbItemCondition = new javax.swing.JLabel();
        txtItemDescription = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listItemCondition = new javax.swing.JList();
        txtSerialNo = new javax.swing.JTextField();
        lbItemModelNo = new javax.swing.JLabel();
        lbItemSerialNo = new javax.swing.JLabel();
        lbItemBrandName = new javax.swing.JLabel();
        txtBrandName = new javax.swing.JTextField();
        txtModelNo = new javax.swing.JTextField();
        lbItemDescrription1 = new javax.swing.JLabel();
        btPayment = new javax.swing.JButton();
        btJobStates = new javax.swing.JButton();
        btAdvanceSearch = new javax.swing.JButton();
        lbServiceOrderID1 = new javax.swing.JLabel();
        cmbServiceOrder = new javax.swing.JComboBox();
        chkWorkFinish = new javax.swing.JCheckBox();
        lbCurrentCost = new javax.swing.JLabel();
        txtCurrentCost = new javax.swing.JTextField();
        lbFinished = new javax.swing.JLabel();

        setOpaque(false);

        btSearch.setText("Search");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });
        btSearch.setBounds(290, 110, 90, 23);
        jLayeredPane1.add(btSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Detail"));

        lbCustName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCustName.setText("Customer Name");
        lbCustName.setBounds(20, 30, 140, 15);
        jLayeredPane2.add(lbCustName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbCustAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCustAddress.setText("Customer Address");
        lbCustAddress.setBounds(20, 70, 140, 15);
        jLayeredPane2.add(lbCustAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbContactNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbContactNo.setText("Contact No.");
        lbContactNo.setBounds(600, 30, 100, 15);
        jLayeredPane2.add(lbContactNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtCustName.setEditable(false);
        txtCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustNameActionPerformed(evt);
            }
        });
        txtCustName.setBounds(180, 30, 330, 25);
        jLayeredPane2.add(txtCustName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtContactNo.setEditable(false);
        txtContactNo.setBounds(720, 30, 200, 25);
        jLayeredPane2.add(txtContactNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtCustAddress.setEditable(false);
        txtCustAddress.setBounds(180, 70, 540, 25);
        jLayeredPane2.add(txtCustAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(30, 140, 940, 110);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Item Detail"));

        lbItemCondition.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbItemCondition.setText("Item Condition");
        lbItemCondition.setBounds(20, 110, 140, 15);
        jLayeredPane3.add(lbItemCondition, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtItemDescription.setEditable(false);
        txtItemDescription.setBounds(180, 70, 330, 25);
        jLayeredPane3.add(txtItemDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane1.setViewportView(listItemCondition);

        jScrollPane1.setBounds(180, 110, 460, 70);
        jLayeredPane3.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtSerialNo.setEditable(false);
        txtSerialNo.setBounds(720, 30, 200, 25);
        jLayeredPane3.add(txtSerialNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbItemModelNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbItemModelNo.setText("Model No ");
        lbItemModelNo.setBounds(20, 30, 110, 15);
        jLayeredPane3.add(lbItemModelNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbItemSerialNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbItemSerialNo.setText("Serial No");
        lbItemSerialNo.setBounds(600, 30, 80, 14);
        jLayeredPane3.add(lbItemSerialNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbItemBrandName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbItemBrandName.setText("Item Brand Name");
        lbItemBrandName.setBounds(600, 70, 120, 14);
        jLayeredPane3.add(lbItemBrandName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtBrandName.setEditable(false);
        txtBrandName.setBounds(720, 70, 200, 25);
        jLayeredPane3.add(txtBrandName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtModelNo.setEditable(false);
        txtModelNo.setBounds(180, 30, 190, 25);
        jLayeredPane3.add(txtModelNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbItemDescrription1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbItemDescrription1.setText("Item Descrription");
        lbItemDescrription1.setBounds(20, 70, 150, 15);
        jLayeredPane3.add(lbItemDescrription1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBounds(30, 260, 940, 200);
        jLayeredPane1.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btPayment.setText("Payment");
        btPayment.setBounds(890, 540, 100, 23);
        jLayeredPane1.add(btPayment, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btJobStates.setText("Job States");
        btJobStates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJobStatesActionPerformed(evt);
            }
        });
        btJobStates.setBounds(770, 540, 110, 23);
        jLayeredPane1.add(btJobStates, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btAdvanceSearch.setText("Advance Search");
        btAdvanceSearch.setBounds(620, 540, 140, 23);
        jLayeredPane1.add(btAdvanceSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbServiceOrderID1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbServiceOrderID1.setText("Service Order ID");
        lbServiceOrderID1.setBounds(30, 110, 110, 20);
        jLayeredPane1.add(lbServiceOrderID1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cmbServiceOrder.setEditable(true);
        cmbServiceOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbServiceOrderKeyReleased(evt);
            }
        });
        cmbServiceOrder.setBounds(150, 110, 120, 20);
        jLayeredPane1.add(cmbServiceOrder, javax.swing.JLayeredPane.DEFAULT_LAYER);

        chkWorkFinish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chkWorkFinish.setText("      Work Finish");
        chkWorkFinish.setOpaque(false);
        chkWorkFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkWorkFinishActionPerformed(evt);
            }
        });
        chkWorkFinish.setBounds(40, 470, 230, 30);
        jLayeredPane1.add(chkWorkFinish, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbCurrentCost.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCurrentCost.setText("Total Cost");
        lbCurrentCost.setBounds(630, 470, 100, 20);
        jLayeredPane1.add(lbCurrentCost, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtCurrentCost.setEditable(false);
        txtCurrentCost.setBounds(750, 470, 190, 25);
        jLayeredPane1.add(txtCurrentCost, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbFinished.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbFinished.setBounds(50, 510, 460, 30);
        jLayeredPane1.add(lbFinished, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btJobStatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJobStatesActionPerformed
        ServiceItem item=new ServiceItem(Item_Code, txtItemDescription.getText(), null, null, null, 0.0, null,false, cmbServiceOrder.getSelectedItem()+"");
       // checkJobsDetail=new CheckJobsDetail(this, pan,item);
        pan.removeAll();
       // checkJobsDetail.setVisible(true);
       // pan.add(checkJobsDetail);
        pan.revalidate();
    }//GEN-LAST:event_btJobStatesActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
       viewServiceOrder();
    }//GEN-LAST:event_btSearchActionPerformed

    private void cmbServiceOrderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbServiceOrderKeyReleased

    }//GEN-LAST:event_cmbServiceOrderKeyReleased

    private void txtCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustNameActionPerformed

    private void chkWorkFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkWorkFinishActionPerformed
        chkWorkFinish.setSelected(false);
    }//GEN-LAST:event_chkWorkFinishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdvanceSearch;
    private javax.swing.JButton btJobStates;
    private javax.swing.JButton btPayment;
    private javax.swing.JButton btSearch;
    private javax.swing.JCheckBox chkWorkFinish;
    private javax.swing.JComboBox cmbServiceOrder;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbContactNo;
    private javax.swing.JLabel lbCurrentCost;
    private javax.swing.JLabel lbCustAddress;
    private javax.swing.JLabel lbCustName;
    private javax.swing.JLabel lbFinished;
    private javax.swing.JLabel lbItemBrandName;
    private javax.swing.JLabel lbItemCondition;
    private javax.swing.JLabel lbItemDescrription1;
    private javax.swing.JLabel lbItemModelNo;
    private javax.swing.JLabel lbItemSerialNo;
    private javax.swing.JLabel lbServiceOrderID1;
    private javax.swing.JList listItemCondition;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtCurrentCost;
    private javax.swing.JTextField txtCustAddress;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtItemDescription;
    private javax.swing.JTextField txtModelNo;
    private javax.swing.JTextField txtSerialNo;
    // End of variables declaration//GEN-END:variables

    private void viewServiceOrder() {
        ServiceOrder serviceOrder=new ServiceOrder();
        serviceOrder.setService_Order_ID(cmbServiceOrder.getSelectedItem()+"");
        try {
            modelList = ServiceOrderControl.viewServiceOrder(serviceOrder);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CheckServiceOrder.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CheckServiceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        serviceOrder=(ServiceOrder)modelList.get("ServiceOrder");
        Customer customer=(Customer)modelList.get("Customer");
        ServiceItem item=(ServiceItem)modelList.get("Item");
        ArrayList<Condition> conditionList=(ArrayList<Condition>)modelList.get("ConditionList");
        Item_Code=item.getItem_Code();
        txtCurrentCost.setText(serviceOrder.getTotal_Cost_Amount()+"");
        txtCustName.setText(customer.getCustName());
        txtCustAddress.setText(customer.getCustAddress());
        txtContactNo.setText(customer.getContactNo());
        txtModelNo.setText(item.getModel_No());
        txtSerialNo.setText(item.getSerial_No());
        txtBrandName.setText(item.getItem_Brand_Name());
        txtItemDescription.setText(item.getDescription());
        DefaultListModel dlm=new DefaultListModel();
        for (Condition condition : conditionList) {
            dlm.addElement(condition.getCondition_Description());
        }
        listItemCondition.setModel(dlm);
        
        if (!(item.getWork_Finish_Date()==null)) {
            chkWorkFinish.setSelected(true);
            if (item.isItem_Can_Be_Repair()) {
                lbFinished.setText("Item Repair Compileted..");
            }else{
                lbFinished.setText("Item Cann't Repair...");
            }
        }
    }
    private void comboControl(JComboBox controlcmb){
        JTextField txt = (JTextField) controlcmb.getEditor().getEditorComponent();
        txt.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    viewServiceOrder();
                }
            }
        });
    }
    private Date setDateTime(String dateString){
       SimpleDateFormat SDF=new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
       Date date = null;
        try {
            date = SDF.parse(dateString);
        } catch (ParseException ex) {
            Logger.getLogger(CheckServiceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
      // System.out.println(date);
       return date;
    }

}
