/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CheckJobStates.java
 *
 * Created on Feb 11, 2012, 3:47:36 PM
 */

package serviceOrder;

/**
 *
 * @author Amila Karunathilaka
 */
public class CheckJobStates extends javax.swing.JPanel {

    /** Creates new form CheckJobStates */
    public CheckJobStates() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lbJobCode = new javax.swing.JLabel();
        txtJobCode = new javax.swing.JTextField();
        lbServiceOrderID = new javax.swing.JLabel();
        txtServiceOrderID = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        lbStates = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listStates = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listRemarks = new javax.swing.JList();
        lbRemarks = new javax.swing.JLabel();

        setOpaque(false);

        lbJobCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbJobCode.setText("Job Code");
        lbJobCode.setBounds(20, 50, 90, 15);
        jLayeredPane2.add(lbJobCode, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtJobCode.setEditable(false);
        txtJobCode.setBounds(170, 50, 140, 25);
        jLayeredPane2.add(txtJobCode, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbServiceOrderID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbServiceOrderID.setText("Service Order ID");
        lbServiceOrderID.setBounds(20, 10, 120, 15);
        jLayeredPane2.add(lbServiceOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtServiceOrderID.setEditable(false);
        txtServiceOrderID.setBounds(170, 10, 140, 25);
        jLayeredPane2.add(txtServiceOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(20, 60, 590, 90);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbStates.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbStates.setText("States");
        lbStates.setBounds(40, 20, 90, 20);
        jLayeredPane3.add(lbStates, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane2.setViewportView(listStates);

        jScrollPane2.setBounds(130, 20, 430, 140);
        jLayeredPane3.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane3.setViewportView(listRemarks);

        jScrollPane3.setBounds(130, 190, 430, 140);
        jLayeredPane3.add(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbRemarks.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbRemarks.setText("Remarks");
        lbRemarks.setBounds(40, 190, 90, 20);
        jLayeredPane3.add(lbRemarks, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBounds(30, 170, 590, 380);
        jLayeredPane1.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbJobCode;
    private javax.swing.JLabel lbRemarks;
    private javax.swing.JLabel lbServiceOrderID;
    private javax.swing.JLabel lbStates;
    private javax.swing.JList listRemarks;
    private javax.swing.JList listStates;
    private javax.swing.JTextField txtJobCode;
    private javax.swing.JTextField txtServiceOrderID;
    // End of variables declaration//GEN-END:variables

}
