/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package serviceOrder;

import control.JobDetailControl;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.ServiceItem;
import model.JobDescription;
import model.JobDetail;
import model.ServiceOrder;
import technician.ConfirmJobComplete;
import technician.TechnicianMain;

/**
 *
 * @author Amila
 */
public class ViewJobDetail extends javax.swing.JPanel {
    Map<String, Object> modelList;
    ServiceOrderMain serviceOrderMain;
    ConfirmJobComplete confirmJobComplete;
    JPanel pan;
    DefaultTableModel dtm;
    ServiceOrder serviceOrder;
    /**
     * Creates new form MyJobDetail
     */
    public ViewJobDetail(ServiceOrderMain serviceOrderMain,JPanel pan,ServiceOrder serviceOrder) {
        initComponents();
        this.serviceOrderMain=serviceOrderMain;
        this.pan=pan;
        this.serviceOrder=serviceOrder;
        dtm=(DefaultTableModel)tbJobDetail.getModel();
        viewJobsForServiceOrder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lbItemDescrription = new javax.swing.JLabel();
        txtItemDescription = new javax.swing.JTextField();
        lbServiceOrderID = new javax.swing.JLabel();
        lbItemBrandName = new javax.swing.JLabel();
        txtServiceOrderID = new javax.swing.JTextField();
        txtItemBrandName = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        lbDescription = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listDescription = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbJobDetail = new javax.swing.JTable();
        btSelectJobAccessoriesDetail = new javax.swing.JButton();
        btJobStates = new javax.swing.JButton();
        btSelectJobTeam = new javax.swing.JButton();
        btback = new javax.swing.JButton();

        lbItemDescrription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbItemDescrription.setText("Item Description");
        lbItemDescrription.setBounds(20, 90, 130, 15);
        jLayeredPane2.add(lbItemDescrription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtItemDescription.setEditable(false);
        txtItemDescription.setBounds(170, 90, 420, 22);
        jLayeredPane2.add(txtItemDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbServiceOrderID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbServiceOrderID.setText("Service Order ID");
        lbServiceOrderID.setBounds(20, 10, 120, 15);
        jLayeredPane2.add(lbServiceOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbItemBrandName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbItemBrandName.setText("Item Brand Name");
        lbItemBrandName.setBounds(20, 50, 130, 15);
        jLayeredPane2.add(lbItemBrandName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtServiceOrderID.setEditable(false);
        txtServiceOrderID.setBounds(170, 10, 150, 22);
        jLayeredPane2.add(txtServiceOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtItemBrandName.setEditable(false);
        txtItemBrandName.setBounds(170, 50, 230, 22);
        jLayeredPane2.add(txtItemBrandName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(20, 80, 890, 130);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbDescription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDescription.setText("Description");
        lbDescription.setBounds(40, 150, 90, 20);
        jLayeredPane3.add(lbDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane2.setViewportView(listDescription);

        jScrollPane2.setBounds(160, 150, 600, 90);
        jLayeredPane3.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tbJobDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job Code", "Job Deficiency", "Start Date ", "Finish Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbJobDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbJobDetailMouseClicked(evt);
            }
        });
        tbJobDetail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbJobDetailFocusGained(evt);
            }
        });
        tbJobDetail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbJobDetailKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tbJobDetail);
        tbJobDetail.getColumnModel().getColumn(0).setPreferredWidth(10);
        tbJobDetail.getColumnModel().getColumn(2).setPreferredWidth(10);
        tbJobDetail.getColumnModel().getColumn(3).setPreferredWidth(10);

        jScrollPane3.setBounds(12, 10, 950, 120);
        jLayeredPane3.add(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btSelectJobAccessoriesDetail.setText("Select Job Accessories Detail");
        btSelectJobAccessoriesDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectJobAccessoriesDetailActionPerformed(evt);
            }
        });
        btSelectJobAccessoriesDetail.setBounds(460, 260, 210, 30);
        jLayeredPane3.add(btSelectJobAccessoriesDetail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btJobStates.setText("Job States");
        btJobStates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJobStatesActionPerformed(evt);
            }
        });
        btJobStates.setBounds(680, 260, 110, 30);
        jLayeredPane3.add(btJobStates, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btSelectJobTeam.setText("Select Job  Team");
        btSelectJobTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectJobTeamActionPerformed(evt);
            }
        });
        btSelectJobTeam.setBounds(800, 260, 150, 30);
        jLayeredPane3.add(btSelectJobTeam, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBounds(10, 220, 980, 300);
        jLayeredPane1.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btback.setText("Back");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });
        btback.setBounds(890, 530, 100, 30);
        jLayeredPane1.add(btback, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbJobDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbJobDetailMouseClicked
        viewJobDeficiency();
    }//GEN-LAST:event_tbJobDetailMouseClicked

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        //pan.removeAll();
       // checkServiceOrder.setVisible(true);
       // pan.add(checkServiceOrder);
       // pan.revalidate();
       // pan.repaint();
    }//GEN-LAST:event_btbackActionPerformed

    private void btSelectJobAccessoriesDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectJobAccessoriesDetailActionPerformed
        //CheckJobStates checkJobStates = new CheckJobStates();
        //pan.removeAll();
       // checkJobStates.setVisible(true);
       // pan.add(checkJobStates);
       // pan.revalidate();
    }//GEN-LAST:event_btSelectJobAccessoriesDetailActionPerformed

    private void btJobStatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJobStatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btJobStatesActionPerformed

    private void tbJobDetailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbJobDetailFocusGained
 
    }//GEN-LAST:event_tbJobDetailFocusGained

    private void tbJobDetailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbJobDetailKeyReleased

    }//GEN-LAST:event_tbJobDetailKeyReleased

    private void btSelectJobTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectJobTeamActionPerformed
        //CheckJobStates checkJobStates = new CheckJobStates();
        //pan.removeAll();
        // checkJobStates.setVisible(true);
        // pan.add(checkJobStates);
        // pan.revalidate();
    }//GEN-LAST:event_btSelectJobTeamActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btJobStates;
    private javax.swing.JButton btSelectJobAccessoriesDetail;
    private javax.swing.JButton btSelectJobTeam;
    private javax.swing.JButton btback;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbDescription;
    private javax.swing.JLabel lbItemBrandName;
    private javax.swing.JLabel lbItemDescrription;
    private javax.swing.JLabel lbServiceOrderID;
    private javax.swing.JList listDescription;
    private javax.swing.JTable tbJobDetail;
    private javax.swing.JTextField txtItemBrandName;
    private javax.swing.JTextField txtItemDescription;
    private javax.swing.JTextField txtServiceOrderID;
    // End of variables declaration//GEN-END:variables
    private void viewJobsForServiceOrder() {
        try {
            modelList=JobDetailControl.viewJobDetail(serviceOrder);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ViewJobDetail.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ViewJobDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
        ServiceItem item=(ServiceItem) modelList.get("Item");
        txtItemDescription.setText(item.getDescription());
        txtServiceOrderID.setText(item.getItem_Brand_Name());
        ArrayList<JobDetail> jobDetailList=(ArrayList<JobDetail>) modelList.get("JobDetail");
        for (JobDetail jobDetail : jobDetailList) {
            Object[] row={jobDetail.getJob_Code(),jobDetail.getJob_Deficiency(),jobDetail.getStart_Date(),jobDetail.getFinish_Date()};
            dtm.addRow(row);
        }
        tbJobDetail.requestFocus();
    }
    private void viewJobDeficiency(){
        ArrayList<JobDescription> jobDescriptionList=(ArrayList<JobDescription>) modelList.get("JobDescriptionList");
        DefaultListModel<String> dlm=new DefaultListModel<String>();
        for (JobDescription description : jobDescriptionList) {
            JobDescription jobDescription=new JobDescription(0, description.getJob_Description(), tbJobDetail.getValueAt(tbJobDetail.getSelectedRow(), 0)+"");
            if (description.equals(jobDescription)) {
                dlm.addElement(description.getJob_Description());
            }
        }
        listDescription.setModel(dlm);
    }
    private void comboControl(JComboBox controlcmb){
        JTextField txt = (JTextField) controlcmb.getEditor().getEditorComponent();
        txt.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    viewJobsForServiceOrder();
                }
            }
        });
    }
    
    private void clear(){
        txtServiceOrderID.setText("");
        txtItemDescription.setText("");
        int rowcount=tbJobDetail.getRowCount();
        for (int i = 0; i < rowcount; i++) {
            dtm.removeRow(0);
        }
    }
}
