/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package setting;

import componentControl.ThemesControl;
import dataFilesControl.FileUtil;
import dataFilesControl.ReadFile;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import transparentBackground.TransferenceThisWindow;
import transparentBackground.TransparentBackgroundForJDialog;

/**
 *
 * @author Amila
 */
public class ConfigurationMain extends javax.swing.JDialog {
    DatabaseConnectionSetting databaseConnectionSetting;
    DatabaseBackupRestore databaseBackupRestore;
    ThemeSetting themeSetting;
    javax.swing.Timer t;
   // TransparentBackgroundForJDialog transparentBackgroundForJDialog=new TransparentBackgroundForJDialog(this);
    /**
     * Creates new form ConfigurationMain
     */
    public ConfigurationMain(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTransparent();
        setBackground();
        checkbtback();
    }
    public ConfigurationMain(java.awt.Frame parent, boolean modal,FileUtil fileUtil,boolean start,Timer t) {
        super(parent, modal);
        initComponents();
        setTransparent();
        setBackground();
        checkbtback();
        this.t=t;
        if (start) {
            databaseConnectionSetting=new DatabaseConnectionSetting(this, pan,fileUtil);
            pan.removeAll();
            databaseConnectionSetting.setVisible(true);
            pan.add(databaseConnectionSetting);
            pan.revalidate();
            repaint();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        btThemeConfiguration1 = new javax.swing.JButton();
        btThemeConfiguration2 = new javax.swing.JButton();
        btDatabaseBackupRestore = new javax.swing.JButton();
        pan = new javax.swing.JPanel();
        btBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1020, 650));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 650, 1020, new javax.swing.ImageIcon(getClass().getResource("/pictures/setting/ConfigurationMain.png")))); // NOI18N

        btThemeConfiguration1.setText("Theme Configuration");
        btThemeConfiguration1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemeConfiguration1ActionPerformed(evt);
            }
        });
        btThemeConfiguration1.setBounds(20, 140, 170, 23);
        jLayeredPane2.add(btThemeConfiguration1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btThemeConfiguration2.setText("Database Connection");
        btThemeConfiguration2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemeConfiguration2ActionPerformed(evt);
            }
        });
        btThemeConfiguration2.setBounds(20, 210, 170, 23);
        jLayeredPane2.add(btThemeConfiguration2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btDatabaseBackupRestore.setText("Database Configuration");
        btDatabaseBackupRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDatabaseBackupRestoreActionPerformed(evt);
            }
        });
        btDatabaseBackupRestore.setBounds(20, 270, 170, 23);
        jLayeredPane2.add(btDatabaseBackupRestore, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pan.setOpaque(false);
        pan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panMouseExited(evt);
            }
        });
        pan.setLayout(new java.awt.BorderLayout());
        pan.setBounds(250, 100, 750, 520);
        jLayeredPane2.add(pan, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        btBack.setBounds(50, 560, 120, 40);
        jLayeredPane2.add(btBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.add(jLayeredPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThemeConfiguration2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemeConfiguration2ActionPerformed
        databaseConnectionSetting=new DatabaseConnectionSetting(this, pan);
        pan.removeAll();
        databaseConnectionSetting.setVisible(true);
        pan.add(databaseConnectionSetting);
        pan.revalidate();
        repaint();
    }//GEN-LAST:event_btThemeConfiguration2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (t==null) {
           dispose(); 
        }else{
           t.start();
           dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void btDatabaseBackupRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDatabaseBackupRestoreActionPerformed
        databaseBackupRestore=new DatabaseBackupRestore(this, pan);
        pan.removeAll();
        databaseBackupRestore.setVisible(true);
        pan.add(databaseBackupRestore);
        pan.revalidate();
        repaint();
    }//GEN-LAST:event_btDatabaseBackupRestoreActionPerformed

    private void btThemeConfiguration1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemeConfiguration1ActionPerformed
        themeSetting=new ThemeSetting(this, pan);
        pan.removeAll();
        themeSetting.setVisible(true);
        pan.add(themeSetting);
        pan.revalidate();
        repaint();
    }//GEN-LAST:event_btThemeConfiguration1ActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        if (t==null) {
           this.dispose(); 
        }else{
           t.start();
           this.dispose();
        }
    }//GEN-LAST:event_btBackActionPerformed

    private void panMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panMouseEntered
        checkbtback();
    }//GEN-LAST:event_panMouseEntered

    private void panMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panMouseExited
        checkbtback();
    }//GEN-LAST:event_panMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigurationMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigurationMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigurationMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigurationMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ConfigurationMain dialog = new ConfigurationMain(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btDatabaseBackupRestore;
    private javax.swing.JButton btThemeConfiguration1;
    private javax.swing.JButton btThemeConfiguration2;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pan;
    // End of variables declaration//GEN-END:variables
    private void setBackground(){
        ThemesControl.setTheme(this,ReadFile.getThemespathinFile());
        setLocationRelativeTo(null);
        final String title="SUMANADASA ELECTRONIC & ELECTRICAL MANAGEMENT SYSTEM";
        setIconImage(new ImageIcon(getClass().getResource("/pictures/Neotech.png")).getImage());
        new Thread(){
            public void run(){
                boolean check=true;
                while (true) {                    
                    for (int i = 0; i < title.length()+1; i++) {
                        setTitle(title.substring(0, i));
                        try {   
                            Thread.sleep(150); 
                        } catch (Exception e) {
                        }
                    }
                    try {   
                        Thread.sleep(800); 
                    } catch (Exception e) {
                    }
                }
           }
        }.start();
    }
    private void setTransparent(){
        TransferenceThisWindow.tranceferantThis(this);
        setSize(1020,650);
    }
    private void checkbtback(){
        if(ReadFile.checkFileExists("DBConnection.txt")){
              btBack.setEnabled(true);
        }else{
            btBack.setEnabled(false);
        }
    }
}
