/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package setting;

import connection.DBConnectionControl;
import dataFilesControl.FileUtil;
import dataFilesControl.ReadFile;
import dataFilesControl.WriteFile;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Amila
 */
public class DatabaseConnectionSetting extends javax.swing.JPanel {

    String driver;
    String host;
    String className;
    String userName;
    String password;
    String databaseURL;
    FileUtil fileUtil;
    ConfigurationMain configurationMain;
    JPanel pan;
    AddNewHost addNewHost;

    /**
     * Creates new form DatabaseConnectionSetting
   this.configurationMain = configurationMain;
        this.pan = pan;
    }   */
    public DatabaseConnectionSetting(ConfigurationMain configurationMain, JPanel pan) {
        initComponents();
        setLoadView();
        this.configurationMain = configurationMain;
        this.pan = pan;
    }
     public DatabaseConnectionSetting(ConfigurationMain configurationMain, JPanel pan,FileUtil fileUtil) {
        initComponents();
        setLoadView();
        this.configurationMain = configurationMain;
        this.pan = pan;
        this.fileUtil=fileUtil;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lbDriverName = new javax.swing.JLabel();
        lbClassName = new javax.swing.JLabel();
        lbHost = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        lbDatabases = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtClassName = new javax.swing.JTextField();
        txtDriverName = new javax.swing.JTextField();
        txtURL = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        cmdDatabases = new javax.swing.JComboBox();
        cmdHost = new javax.swing.JComboBox();
        txtUserName = new javax.swing.JTextField();
        lbSetConnection = new javax.swing.JLabel();
        btsetConnection = new javax.swing.JLabel();
        btSetNewHost = new javax.swing.JButton();

        setOpaque(false);

        lbDriverName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDriverName.setForeground(new java.awt.Color(51, 51, 51));
        lbDriverName.setText("Driver Name");
        lbDriverName.setBounds(40, 80, 130, 15);
        jLayeredPane1.add(lbDriverName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbClassName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbClassName.setForeground(new java.awt.Color(51, 51, 51));
        lbClassName.setText("Class  Name");
        lbClassName.setBounds(40, 130, 130, 15);
        jLayeredPane1.add(lbClassName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbHost.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbHost.setForeground(new java.awt.Color(51, 51, 51));
        lbHost.setText("Host");
        lbHost.setBounds(40, 180, 130, 15);
        jLayeredPane1.add(lbHost, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbUserName.setForeground(new java.awt.Color(51, 51, 51));
        lbUserName.setText("User Name");
        lbUserName.setBounds(40, 230, 90, 15);
        jLayeredPane1.add(lbUserName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(51, 51, 51));
        lbPassword.setText("Password");
        lbPassword.setBounds(40, 280, 120, 15);
        jLayeredPane1.add(lbPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbDatabases.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDatabases.setForeground(new java.awt.Color(51, 51, 51));
        lbDatabases.setText("Database");
        lbDatabases.setBounds(40, 330, 120, 15);
        jLayeredPane1.add(lbDatabases, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("JDBC URL");
        jLabel7.setBounds(40, 400, 110, 15);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtClassName.setEditable(false);
        txtClassName.setText("com.mysql.jdbc.Driver");
        txtClassName.setBounds(200, 130, 230, 25);
        jLayeredPane1.add(txtClassName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtDriverName.setEditable(false);
        txtDriverName.setText("MySQL (Conector/J Driver)");
        txtDriverName.setBounds(200, 80, 230, 25);
        jLayeredPane1.add(txtDriverName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtURL.setEditable(false);
        txtURL.setBounds(200, 400, 460, 25);
        jLayeredPane1.add(txtURL, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        txtPassword.setBounds(200, 280, 170, 25);
        jLayeredPane1.add(txtPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cmdDatabases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDatabasesActionPerformed(evt);
            }
        });
        cmdDatabases.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmdDatabasesFocusGained(evt);
            }
        });
        cmdDatabases.setBounds(200, 330, 230, 25);
        jLayeredPane1.add(cmdDatabases, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cmdHost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmdHostFocusGained(evt);
            }
        });
        cmdHost.setBounds(200, 180, 230, 25);
        jLayeredPane1.add(cmdHost, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtUserName.setBounds(200, 230, 170, 25);
        jLayeredPane1.add(txtUserName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbSetConnection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/setting/Tips45.png"))); // NOI18N
        lbSetConnection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSetConnectionMouseEntered(evt);
            }
        });
        lbSetConnection.setBounds(310, 450, 50, 50);
        jLayeredPane1.add(lbSetConnection, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btsetConnection.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btsetConnection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/setting/Tips60.png"))); // NOI18N
        btsetConnection.setText("Set Connection");
        btsetConnection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btsetConnectionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btsetConnectionMouseExited(evt);
            }
        });
        btsetConnection.setBounds(300, 440, 180, 60);
        jLayeredPane1.add(btsetConnection, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btSetNewHost.setText("Set New Host");
        btSetNewHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSetNewHostActionPerformed(evt);
            }
        });
        btSetNewHost.setBounds(460, 180, 110, 30);
        jLayeredPane1.add(btSetNewHost, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdDatabasesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmdDatabasesFocusGained
    }//GEN-LAST:event_cmdDatabasesFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
    }//GEN-LAST:event_txtPasswordFocusLost

    private void cmdDatabasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDatabasesActionPerformed
        String database = cmdDatabases.getSelectedItem() + "";
        databaseURL = driver + "//" + host + "/" + database;
        txtURL.setText(databaseURL);
    }//GEN-LAST:event_cmdDatabasesActionPerformed

    private void lbSetConnectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSetConnectionMouseEntered
        lbSetConnection.setVisible(false);
        btsetConnection.setVisible(true);
    }//GEN-LAST:event_lbSetConnectionMouseEntered

    private void btsetConnectionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsetConnectionMouseExited
        btsetConnection.setVisible(false);
        lbSetConnection.setVisible(true);
    }//GEN-LAST:event_btsetConnectionMouseExited

    private void btsetConnectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsetConnectionMouseClicked
        int res = JOptionPane.showConfirmDialog(this, "Do you want to set Database Connection?", "Database Connection", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            setDBConnection();
        }
    }//GEN-LAST:event_btsetConnectionMouseClicked

    private void btSetNewHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSetNewHostActionPerformed
        addNewHost = new AddNewHost(null, true, cmdHost, this);
        addNewHost.setVisible(true);
    }//GEN-LAST:event_btSetNewHostActionPerformed

    private void cmdHostFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmdHostFocusGained
    }//GEN-LAST:event_cmdHostFocusGained

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        host = cmdHost.getSelectedItem() + "";
        userName = txtUserName.getText();
        password = new String(txtPassword.getPassword());
        try {
            cmdDatabases.removeAllItems();
            ArrayList<String> databaseList = DBConnectionControl.getDatabaseList(className, driver, host, userName, password);
            for (String string : databaseList) {
                cmdDatabases.addItem(string);
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_txtPasswordKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSetNewHost;
    private javax.swing.JLabel btsetConnection;
    private javax.swing.JComboBox cmdDatabases;
    private javax.swing.JComboBox cmdHost;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lbClassName;
    private javax.swing.JLabel lbDatabases;
    private javax.swing.JLabel lbDriverName;
    private javax.swing.JLabel lbHost;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbSetConnection;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JTextField txtClassName;
    private javax.swing.JTextField txtDriverName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtURL;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    public void setLoadView() {
        btsetConnection.setVisible(false);
        try {
            FileReader fr = new FileReader("ConnectionDriver.txt");
            BufferedReader br = new BufferedReader(fr);
            driver = br.readLine();
            if (driver.equals("jdbc:mysql:")) {
                txtDriverName.setText("MySQL (Conector/J Driver)");
            }
        } catch (Exception ex) {
            Logger.getLogger(ReadFile.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            FileReader fr = new FileReader("ConnectionClass.txt");
            BufferedReader br = new BufferedReader(fr);
            className = br.readLine();
            txtClassName.setText(className);
        } catch (Exception ex) {
            Logger.getLogger(ReadFile.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            cmdHost.removeAllItems();
            FileReader fr = new FileReader("ConnectionHosts.txt");
            BufferedReader br = new BufferedReader(fr);
            String host = br.readLine();
            while (host != null) {
                cmdHost.addItem(host);
                host = br.readLine();
            }
        } catch (Exception ex) {
            Logger.getLogger(ReadFile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setDBConnection() {
        try {
            WriteFile.writeDBConnection(className, databaseURL, userName, password);
            fileUtil.setDatabaseConnection(className,driver,host);
            fileUtil.setDatabase(userName,password,databaseURL);
            WriteFile.writeUsingHost(cmdHost.getSelectedItem() + "");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DatabaseConnectionSetting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DatabaseConnectionSetting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
