/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package grn;

import componentControl.AutoGenerate;
import componentControl.ComboSearch;
import componentControl.FillComboBox;
import componentControl.ValidationValues;
import control.GRNControl;
import control.SalesItemControl;
import control.VendorControl;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.*;
import vendor.AddNewVendor;

/**
 *
 * @author Amila
 */
public class AddGRN extends javax.swing.JPanel {

    ArrayList<SalesItem> updatesalesItemList = new ArrayList<SalesItem>();
    DefaultTableModel dtm;
    GRN grn;
    GoodReceiveNoteView goodReceiveNoteView;
    JPanel pan;
    AddNewVendor addNewVendor;
    AddNewItem addNewItem;
    double totalAmount;

    /**
     * Creates new form AddGRN
     */
    public AddGRN(GRN grn, JPanel pan) {
        initComponents();
        this.grn = grn;
        this.pan = pan;
        dtm = (DefaultTableModel) tbSalesItem.getModel();
        txtGRNID.setText(AutoGenerate.getNextID("GRN", "GRN_ID", "GD"));
        FillComboBox.fillComboDatabase(cmbVendorName, "Vendor", "Vendor_Name");
        clear();
        ComboSearch cs1 = new ComboSearch();
        cs1.setSearchableCombo(cmbModelNo, true, "No Model");
    }
    
    public AddGRN(GoodReceiveNoteView goodReceiveNoteView, JPanel pan) {
        initComponents();
        this.goodReceiveNoteView = goodReceiveNoteView;
        this.pan = pan;
        dtm = (DefaultTableModel) tbSalesItem.getModel();
        txtGRNID.setText(AutoGenerate.getNextID("GRN", "GRN_ID", "GD"));
        FillComboBox.fillComboDatabase(cmbVendorName, "Vendor", "Vendor_Name");
        clear();
        ComboSearch cs1 = new ComboSearch();
        cs1.setSearchableCombo(cmbModelNo, true, "No Model");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        lbServiceOrderID = new javax.swing.JLabel();
        txtGRNID = new javax.swing.JTextField();
        lbDate = new javax.swing.JLabel();
        cmbcalOrderDate = new org.freixas.jcalendar.JCalendarCombo();
        lbModelNo = new javax.swing.JLabel();
        cmbModelNo = new javax.swing.JComboBox();
        lbUnitPurchasePrice = new javax.swing.JLabel();
        txtUnitPurchasePrice = new javax.swing.JTextField();
        lbWarrenty = new javax.swing.JLabel();
        txtGRNInvoiceNo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btAdd = new javax.swing.JButton();
        lbDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lbWarrenty1 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        btAddNewSalesItem = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSalesItem = new javax.swing.JTable();
        lbCustAddress2 = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JTextField();
        btaddGRN = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        lbCustomerName = new javax.swing.JLabel();
        cmbVendorName = new javax.swing.JComboBox();
        btAddNewVendor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setOpaque(false);

        jLayeredPane3.setBounds(30, 280, 0, 0);
        jLayeredPane1.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbServiceOrderID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbServiceOrderID.setText("GRN ID");
        lbServiceOrderID.setBounds(30, 30, 160, 20);
        jLayeredPane4.add(lbServiceOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtGRNID.setEditable(false);
        txtGRNID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGRNID.setOpaque(false);
        txtGRNID.setBounds(140, 30, 170, 30);
        jLayeredPane4.add(txtGRNID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDate.setText("Date");
        lbDate.setBounds(720, 30, 70, 20);
        jLayeredPane4.add(lbDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cmbcalOrderDate.setEnabled(false);
        cmbcalOrderDate.setBounds(780, 30, 250, 30);
        jLayeredPane4.add(cmbcalOrderDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbModelNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbModelNo.setText("Model No");
        lbModelNo.setBounds(20, 110, 170, 15);
        jLayeredPane4.add(lbModelNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cmbModelNo.setEditable(true);
        cmbModelNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbModelNoItemStateChanged(evt);
            }
        });
        cmbModelNo.setBounds(40, 130, 220, 30);
        jLayeredPane4.add(cmbModelNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbUnitPurchasePrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbUnitPurchasePrice.setText("Unit Purchase Price");
        lbUnitPurchasePrice.setBounds(20, 180, 130, 15);
        jLayeredPane4.add(lbUnitPurchasePrice, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtUnitPurchasePrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUnitPurchasePrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUnitPurchasePriceFocusGained(evt);
            }
        });
        txtUnitPurchasePrice.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtUnitPurchasePricePropertyChange(evt);
            }
        });
        txtUnitPurchasePrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUnitPurchasePriceKeyReleased(evt);
            }
        });
        txtUnitPurchasePrice.setBounds(80, 200, 220, 30);
        jLayeredPane4.add(txtUnitPurchasePrice, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbWarrenty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbWarrenty.setText("Receive Invoice No");
        lbWarrenty.setBounds(350, 30, 130, 15);
        jLayeredPane4.add(lbWarrenty, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtGRNInvoiceNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtGRNInvoiceNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGRNInvoiceNoFocusGained(evt);
            }
        });
        txtGRNInvoiceNo.setBounds(480, 30, 180, 30);
        jLayeredPane4.add(txtGRNInvoiceNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 2));
        jSeparator1.setBounds(30, 80, 480, 2);
        jLayeredPane4.add(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btAdd.setText("Add Table");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        btAdd.setBounds(940, 220, 110, 30);
        jLayeredPane4.add(btAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbDescription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDescription.setText("Description");
        lbDescription.setBounds(280, 110, 140, 15);
        jLayeredPane4.add(lbDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtDescription.setEditable(false);
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });
        txtDescription.setBounds(310, 130, 440, 30);
        jLayeredPane4.add(txtDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbWarrenty1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbWarrenty1.setText("Quantity");
        lbWarrenty1.setBounds(360, 180, 100, 15);
        jLayeredPane4.add(lbWarrenty1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtQty.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQtyFocusGained(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
        });
        txtQty.setBounds(380, 200, 120, 30);
        jLayeredPane4.add(txtQty, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btAddNewSalesItem.setText("Add New Sales Item");
        btAddNewSalesItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddNewSalesItemActionPerformed(evt);
            }
        });
        btAddNewSalesItem.setBounds(820, 120, 180, 30);
        jLayeredPane4.add(btAddNewSalesItem, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.setBounds(10, 150, 1080, 270);
        jLayeredPane1.add(jLayeredPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setMinimumSize(new java.awt.Dimension(960, 400));
        jLayeredPane2.setPreferredSize(new java.awt.Dimension(960, 500));

        tbSalesItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model No", "Description", "Qty", "Unit Purchase Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbSalesItem);
        tbSalesItem.getColumnModel().getColumn(0).setPreferredWidth(200);
        tbSalesItem.getColumnModel().getColumn(1).setPreferredWidth(400);
        tbSalesItem.getColumnModel().getColumn(2).setPreferredWidth(50);
        tbSalesItem.getColumnModel().getColumn(3).setPreferredWidth(150);
        tbSalesItem.getColumnModel().getColumn(4).setPreferredWidth(150);

        jScrollPane1.setBounds(20, 10, 1040, 150);
        jLayeredPane2.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbCustAddress2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbCustAddress2.setText("Total Amount");
        lbCustAddress2.setBounds(730, 170, 140, 20);
        jLayeredPane2.add(lbCustAddress2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtTotalAmount.setEditable(false);
        txtTotalAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalAmount.setBounds(860, 170, 190, 30);
        jLayeredPane2.add(txtTotalAmount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btaddGRN.setText("Submit");
        btaddGRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddGRNActionPerformed(evt);
            }
        });
        btaddGRN.setBounds(960, 220, 110, 30);
        jLayeredPane2.add(btaddGRN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btRemove.setText("Remove");
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });
        btRemove.setBounds(10, 170, 100, 23);
        jLayeredPane2.add(btRemove, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(10, 420, 1080, 260);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbCustomerName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCustomerName.setText("Vendor Name");
        lbCustomerName.setBounds(20, 20, 130, 20);
        jLayeredPane8.add(lbCustomerName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cmbVendorName.setBounds(170, 20, 420, 30);
        jLayeredPane8.add(cmbVendorName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btAddNewVendor.setText("Add New Vendor");
        btAddNewVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddNewVendorActionPerformed(evt);
            }
        });
        btAddNewVendor.setBounds(900, 20, 150, 30);
        jLayeredPane8.add(btAddNewVendor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane8.setBounds(10, 70, 1080, 70);
        jLayeredPane1.add(jLayeredPane8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 32)); // NOI18N
        jLabel3.setText("Add Goods Receive Note");
        jLabel3.setBounds(40, 10, 380, 50);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbModelNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbModelNoItemStateChanged
    }//GEN-LAST:event_cmbModelNoItemStateChanged

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void btaddGRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddGRNActionPerformed
        addDB();
    }//GEN-LAST:event_btaddGRNActionPerformed

    private void btAddNewVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddNewVendorActionPerformed
        addNewVendor = new AddNewVendor(grn, pan, this);
        this.setVisible(false);
        pan.removeAll();
        addNewVendor.setVisible(true);
        pan.add(addNewVendor);
        pan.revalidate();
    }//GEN-LAST:event_btAddNewVendorActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        addTable();
    }//GEN-LAST:event_btAddActionPerformed

    private void btAddNewSalesItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddNewSalesItemActionPerformed
        addNewItem = new AddNewItem(grn, pan, this);
        this.setVisible(false);
        pan.removeAll();
        addNewItem.setVisible(true);
        pan.add(addNewItem);
        pan.revalidate();
    }//GEN-LAST:event_btAddNewSalesItemActionPerformed

    private void txtUnitPurchasePriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnitPurchasePriceKeyReleased
        ValidationValues.ValidateDoubleValues(txtUnitPurchasePrice);
    }//GEN-LAST:event_txtUnitPurchasePriceKeyReleased

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
        ValidationValues.ValidateIntValue(txtQty);
    }//GEN-LAST:event_txtQtyKeyReleased

    private void txtUnitPurchasePricePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtUnitPurchasePricePropertyChange
        ValidationValues.ValidateCurrency(txtUnitPurchasePrice);
    }//GEN-LAST:event_txtUnitPurchasePricePropertyChange

    private void txtUnitPurchasePriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnitPurchasePriceFocusGained
        txtUnitPurchasePrice.selectAll();
    }//GEN-LAST:event_txtUnitPurchasePriceFocusGained

    private void txtQtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtyFocusGained
        txtQty.selectAll();
    }//GEN-LAST:event_txtQtyFocusGained

    private void txtGRNInvoiceNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGRNInvoiceNoFocusGained
        txtGRNInvoiceNo.selectAll();
    }//GEN-LAST:event_txtGRNInvoiceNoFocusGained

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        int[] selectedRows=tbSalesItem.getSelectedRows();
        for (int i : selectedRows) {
            dtm.removeRow(i);
        }
    }//GEN-LAST:event_btRemoveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btAddNewSalesItem;
    private javax.swing.JButton btAddNewVendor;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btaddGRN;
    private javax.swing.JComboBox cmbModelNo;
    private javax.swing.JComboBox cmbVendorName;
    private org.freixas.jcalendar.JCalendarCombo cmbcalOrderDate;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbCustAddress2;
    private javax.swing.JLabel lbCustomerName;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbDescription;
    private javax.swing.JLabel lbModelNo;
    private javax.swing.JLabel lbServiceOrderID;
    private javax.swing.JLabel lbUnitPurchasePrice;
    private javax.swing.JLabel lbWarrenty;
    private javax.swing.JLabel lbWarrenty1;
    private javax.swing.JTable tbSalesItem;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtGRNID;
    private javax.swing.JTextField txtGRNInvoiceNo;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtTotalAmount;
    private javax.swing.JTextField txtUnitPurchasePrice;
    // End of variables declaration//GEN-END:variables

    private void addDB() {
        try {
            Vendor vendor = new Vendor();
            vendor.setVendor_Name(cmbVendorName.getSelectedItem() + "");
            String transactionID=AutoGenerate.getNextID("Transaction", "", "TR");
            Transaction transaction=new Transaction(transactionID, setDateTime(), TransactionType.GOODRECEIVE.getCode());
            GoodReceiveNote goodReceiveNote = new GoodReceiveNote(txtGRNID.getText(), setDateTime(), Double.parseDouble(txtTotalAmount.getText()), 0.0, txtGRNInvoiceNo.getText(),VendorControl.SearchVendor(vendor).getVendor_ID(),transactionID);
            int res = GRNControl.addGRN(transaction,goodReceiveNote, updatesalesItemList);         
            int rowcount=tbSalesItem.getRowCount();
            for (int i = 0; i < rowcount; i++) {
                GRNDetail gRNDetail=new GRNDetail(txtGRNID.getText(), tbSalesItem.getValueAt(0, 0)+"", Double.parseDouble(tbSalesItem.getValueAt(0, 3)+""), Integer.parseInt(tbSalesItem.getValueAt(0, 2)+""));
                GRNControl.addGRNDetail(gRNDetail);
                tbSalesItem.remove(0);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GRN.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GRN.class.getName()).log(Level.SEVERE, null, ex);
        }
        updatesalesItemList = new ArrayList<SalesItem>();
    }

    private void addTable() {
        try {
            String modelNo = cmbModelNo.getSelectedItem() + "";
            SalesItem salesItemfill=SalesItemControl.getSalesItem(modelNo, "Model_No");
            String brandName = salesItemfill.getItem_Brand_Name();
            String description = txtDescription.getText();
            double unitPurchasePrice = Double.parseDouble(txtUnitPurchasePrice.getText());
            int qty = Integer.parseInt(txtQty.getText());
            String itemTypeCode = salesItemfill.getItemType_Code();
            int rowcount = tbSalesItem.getRowCount();
            int row = -1;
            for (int i = 0; i < rowcount; i++) {
                if (modelNo.equals(tbSalesItem.getValueAt(i, 0) + "")) {
                    row = i;
                }
            }
            if (row >= 0) {
                qty += Integer.parseInt(tbSalesItem.getValueAt(row, 2) + "");
                tbSalesItem.setValueAt(qty, row, 2);
                tbSalesItem.setValueAt(qty * Integer.parseInt(tbSalesItem.getValueAt(row, 3) + ""), row, 5);
                totalAmount += qty * unitPurchasePrice;
                txtTotalAmount.setText(totalAmount + ""); 
                int totalqty = SalesItemControl.getSalesItem(modelNo, "Model_No").getItem_Qty() + qty;
                updatesalesItemList.get(row).setItem_Qty(totalqty);       
            } else {
                Object[] ob = {modelNo, description, qty, unitPurchasePrice, qty * unitPurchasePrice};
                dtm.addRow(ob);
                totalAmount += qty * unitPurchasePrice;
                txtTotalAmount.setText(totalAmount + "");
                SalesItem salesItem=SalesItemControl.getSalesItem(modelNo, "Model_No");
                int totalqty = salesItem.getItem_Qty() + qty;
                updatesalesItemList.get(row).setItem_Qty(totalqty);
                updatesalesItemList.add(salesItem);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddGRN.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddGRN.class.getName()).log(Level.SEVERE, null, ex);
        }
        clear();
    }

    private String setDateTime() {
        SimpleDateFormat SDF = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        String Date = SDF.format(cmbcalOrderDate.getDate());
        System.out.println(Date);
        return Date;
    }

    private void comboControl() {

        JTextField txt1 = (JTextField) cmbModelNo.getEditor().getEditorComponent();
        txt1.addKeyListener(new KeyAdapter() {

            public void keyReleased(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_RIGHT || evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    //checkEmpty();
                } else if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
                    //checkEmpty();
                }
            }
        });
    }
    
    private void clear(){
        txtDescription.setText("");
        txtUnitPurchasePrice.setText("0.00");
        txtUnitPurchasePrice.setText("0.00");
        txtQty.setText("0");
        txtGRNInvoiceNo.setText("");

    }
    
     private void checkbt() {
        if (txtQty.getText().trim().isEmpty()) {
            btAdd.setEnabled(false);
        } else {
            btAdd.setEnabled(true);
        }
        if (updatesalesItemList.isEmpty()) {
            btaddGRN.setEnabled(false);
        } else {
            btaddGRN.setEnabled(true);
        }
    }
}
