/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package grn;

import adminMain.AdminMain;
import cashier.CashierMain;
import componentControl.ThemesControl;
import dataFilesControl.ReadFile;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import login.LoginMain;
import model.SystemUser;

/**
 *
 * @author Amila
 */
public class GoodReceiveNoteView extends javax.swing.JFrame {

    AddGRN addGRN;
    CashierMain cashierMain;
    AdminMain adminMain;
    SystemUser systemUser;
    /**
     * Creates new form GoodReceiveNote
     */
    public GoodReceiveNoteView() {
        initComponents();
        setBackground();
        addGRN = new AddGRN(this, pan);
        pan.removeAll();
        addGRN.setVisible(true);
        pan.add(addGRN);
        pan.revalidate();
    }
    public GoodReceiveNoteView(CashierMain cashierMain, SystemUser systemUser) {
        initComponents();
        this.cashierMain = cashierMain;
        setBackground();
        btLogout.setVisible(false);
        btExit1.setVisible(false);
        addGRN = new AddGRN(this, pan);
        pan.removeAll();
        addGRN.setVisible(true);
        pan.add(addGRN);
        pan.revalidate();
        lbUserName.setText(systemUser.getUser_Name());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        pan = new javax.swing.JPanel();
        btExit1 = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        lbTime = new javax.swing.JLabel();
        servicePane = new javax.swing.JLayeredPane();
        btReceiveServiceOrder = new javax.swing.JButton();
        btCheckServiceOrder = new javax.swing.JButton();
        btInvoice = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();
        btexit = new bir.loader();
        btlogout = new bir.loader();
        btminmized = new bir.loader();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLayeredPane1.setBackground(new java.awt.Color(240, 240, 240));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1024, 1280, new javax.swing.ImageIcon(getClass().getResource("/pictures/grn/GRN 1280,1024.png")))); // NOI18N
        jLayeredPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLayeredPane1KeyReleased(evt);
            }
        });

        pan.setOpaque(false);
        pan.setLayout(new java.awt.BorderLayout());
        pan.setBounds(10, 130, 1100, 680);
        jLayeredPane1.add(pan, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btExit1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btExit1.setText("Exit");
        btExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExit1ActionPerformed(evt);
            }
        });
        btExit1.setBounds(1130, 970, 120, 40);
        jLayeredPane1.add(btExit1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLogout.setText("Logout");
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });
        btLogout.setBounds(1000, 970, 120, 40);
        jLayeredPane1.add(btLogout, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        btBack.setBounds(1060, 970, 130, 40);
        jLayeredPane1.add(btBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbTime.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbTime.setBounds(1110, 100, 160, 40);
        jLayeredPane1.add(lbTime, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btReceiveServiceOrder.setFont(new java.awt.Font("Andalus", 1, 16)); // NOI18N
        btReceiveServiceOrder.setText("Receive Service Order");
        btReceiveServiceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReceiveServiceOrderActionPerformed(evt);
            }
        });
        btReceiveServiceOrder.setBounds(30, 10, 210, 40);
        servicePane.add(btReceiveServiceOrder, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btCheckServiceOrder.setFont(new java.awt.Font("Andalus", 1, 16)); // NOI18N
        btCheckServiceOrder.setText("Check Service Order");
        btCheckServiceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCheckServiceOrderActionPerformed(evt);
            }
        });
        btCheckServiceOrder.setBounds(260, 10, 190, 40);
        servicePane.add(btCheckServiceOrder, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btInvoice.setFont(new java.awt.Font("Andalus", 1, 16)); // NOI18N
        btInvoice.setText("Daily Report");
        btInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInvoiceActionPerformed(evt);
            }
        });
        btInvoice.setBounds(470, 10, 150, 40);
        servicePane.add(btInvoice, javax.swing.JLayeredPane.DEFAULT_LAYER);

        servicePane.setBounds(70, 860, 670, 70);
        jLayeredPane1.add(servicePane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel1.setText("User Name");
        jLabel1.setBounds(10, 100, 100, 20);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbUserName.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        lbUserName.setBounds(110, 100, 210, 30);
        jLayeredPane1.add(lbUserName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/button/exit 30.png"))); // NOI18N
        btexit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/button/exit active 30.png"))); // NOI18N
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });
        btexit.setBounds(1230, 10, 40, 50);
        jLayeredPane1.add(btexit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/button/ Logout 30.png"))); // NOI18N
        btlogout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/button/Logout active 30.png"))); // NOI18N
        btlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlogoutActionPerformed(evt);
            }
        });
        btlogout.setBounds(1190, 10, 40, 50);
        jLayeredPane1.add(btlogout, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btminmized.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/button/Minimized 30.png"))); // NOI18N
        btminmized.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/button/Minimized active 30.png"))); // NOI18N
        btminmized.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btminmizedMouseEntered(evt);
            }
        });
        btminmized.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btminmizedActionPerformed(evt);
            }
        });
        btminmized.setBounds(1150, 10, 40, 50);
        jLayeredPane1.add(btminmized, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExit1ActionPerformed
        int res = JOptionPane.showConfirmDialog(this, "Do You want Exit?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null);
        if (res == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btExit1ActionPerformed

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        int res = JOptionPane.showConfirmDialog(this, "Do You want Logout ?", "Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null);
        if (res == JOptionPane.YES_OPTION) {
            if (adminMain != null) {
                adminMain.dispose();
            } else if (cashierMain != null) {
                cashierMain.dispose();
            }
            this.dispose();
            new LoginMain().setVisible(true);
        }
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        this.dispose();
        if (adminMain != null) {
            adminMain.setVisible(true);
        } else if (cashierMain != null) {
            cashierMain.setVisible(true);
        }
    }//GEN-LAST:event_btBackActionPerformed

    private void btReceiveServiceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReceiveServiceOrderActionPerformed

   }//GEN-LAST:event_btReceiveServiceOrderActionPerformed

    private void btCheckServiceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCheckServiceOrderActionPerformed

   }//GEN-LAST:event_btCheckServiceOrderActionPerformed

    private void btInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInvoiceActionPerformed

   }//GEN-LAST:event_btInvoiceActionPerformed

    private void jLayeredPane1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLayeredPane1KeyReleased

   }//GEN-LAST:event_jLayeredPane1KeyReleased

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        ImageIcon image = new ImageIcon("src\\pictures\\button\\exit active 30.png");
        int res = JOptionPane.showConfirmDialog(this, "Do You want Exit?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, image);
        if (res == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btexitActionPerformed

    private void btlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlogoutActionPerformed
        ImageIcon image = new ImageIcon("src\\pictures\\button\\Logout active 30.png");
        int res = JOptionPane.showConfirmDialog(this, "Do You want Logout ?", "Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, image);
        if (res == JOptionPane.YES_OPTION) {
            if (adminMain != null) {
                adminMain.dispose();
            }
            this.dispose();
            new LoginMain().setVisible(true);
        }
    }//GEN-LAST:event_btlogoutActionPerformed

    private void btminmizedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btminmizedMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btminmizedMouseEntered

    private void btminmizedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btminmizedActionPerformed
        GoodReceiveNoteView.this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btminmizedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GoodReceiveNoteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GoodReceiveNoteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GoodReceiveNoteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GoodReceiveNoteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GoodReceiveNoteView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btCheckServiceOrder;
    private javax.swing.JButton btExit1;
    private javax.swing.JButton btInvoice;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btReceiveServiceOrder;
    private bir.loader btexit;
    private bir.loader btlogout;
    private bir.loader btminmized;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lbTime;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JPanel pan;
    private javax.swing.JLayeredPane servicePane;
    // End of variables declaration//GEN-END:variables
 private void setClock() {
        Timer timer = new Timer(500, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sdf1 = new SimpleDateFormat("hh : mm : ss aa");
                String time = sdf1.format(d);
                lbTime.setText(time);
            }
        });
        timer.start();
    }

    private void setBackground() {
        ThemesControl.setTheme(this, ReadFile.getThemespathinFile());
        setLocationRelativeTo(null);
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        System.out.println(Toolkit.getDefaultToolkit().getScreenSize());
        final String title = "SUMANADASA ELECTRONIC & ELECTRICAL MANAGEMENT SYSTEM";
        setIconImage(new ImageIcon(getClass().getResource("/pictures/Neotech.png")).getImage());
        setClock();
        new Thread() {

            public void run() {
                boolean check = true;
                while (true) {
                    for (int i = 0; i < title.length() + 1; i++) {
                        setTitle(title.substring(0, i));
                        try {
                            Thread.sleep(150);
                        } catch (Exception e) {
                        }
                    }
                    try {
                        Thread.sleep(800);
                    } catch (Exception e) {
                    }
                }
            }
        }.start();
    }
}
