/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jobDetail;

import cashier.AddServiceOrder;
import cashier.CashierMain;
import componentControl.AutoGenerate;
import control.JobDetailControl;
import control.ServiceOrderControl;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.*;
import printreport.ReportControl;
import technician.AddJodDetail;
import technician.ServiceOrderDetail;

/**
 *
 * @author Amila
 */
public class AddJobDetail extends javax.swing.JPanel {

    ServiceOrder serviceOrder;
    ServiceItem item;
    Customer customer;
    ServiceOrderDetail serviceOrderDetail;
    Map<String, Object> modelList;
    ArrayList<AccessoriesDetail> accessoriesDetailList;
    ArrayList<EmployeeDetail> employeeDetailList;
    Map<String, Object> orderList;
    DefaultListModel<String> dlm;
    CashierMain cashierMain;
    JPanel pan;
    AddServiceOrder addServiceOrder;
    String Item_Code;

    /**
     * Creates new form AddJobDetail
     */
    public AddJobDetail(CashierMain cashierMain, JPanel pan, Map<String, Object> orderList, AddServiceOrder addServiceOrder) {
        initComponents();
        this.cashierMain = cashierMain;
        this.pan = pan;
        this.addServiceOrder = addServiceOrder;
        this.orderList = orderList;
        viewServiceOrder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lbJobCode = new javax.swing.JLabel();
        lbJobDeficiency = new javax.swing.JLabel();
        txtJobDeficiency = new javax.swing.JTextField();
        txtJobCode = new javax.swing.JTextField();
        lbAddJobDescription = new javax.swing.JLabel();
        txtAddJobDescription = new javax.swing.JTextField();
        btmoveJobDescription = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listJobDescription = new javax.swing.JList();
        btReceiveAccessories = new javax.swing.JButton();
        bEmployeeChargeDetail = new javax.swing.JButton();
        btStates1 = new javax.swing.JButton();
        chkPrintServiceOrder = new javax.swing.JCheckBox();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        lbServiceOrderID = new javax.swing.JLabel();
        lbItemDescription = new javax.swing.JLabel();
        lbBrandName = new javax.swing.JLabel();
        txtBrandName = new javax.swing.JTextField();
        txtItemDescription = new javax.swing.JTextField();
        txtServiceOrderID = new javax.swing.JTextField();
        btaddJob = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btback = new javax.swing.JButton();

        setOpaque(false);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("New Job  Detail"));

        lbJobCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbJobCode.setText("Job Code");
        lbJobCode.setBounds(50, 50, 110, 15);
        jLayeredPane2.add(lbJobCode, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbJobDeficiency.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbJobDeficiency.setText("Job Deficiency");
        lbJobDeficiency.setBounds(50, 90, 120, 15);
        jLayeredPane2.add(lbJobDeficiency, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtJobDeficiency.setBounds(180, 90, 430, 25);
        jLayeredPane2.add(txtJobDeficiency, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtJobCode.setEditable(false);
        txtJobCode.setBounds(180, 50, 160, 25);
        jLayeredPane2.add(txtJobCode, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbAddJobDescription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbAddJobDescription.setText("Add Job Description");
        lbAddJobDescription.setBounds(50, 150, 150, 15);
        jLayeredPane2.add(lbAddJobDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtAddJobDescription.setBounds(50, 180, 350, 25);
        jLayeredPane2.add(txtAddJobDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btmoveJobDescription.setText(">>");
        btmoveJobDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmoveJobDescriptionActionPerformed(evt);
            }
        });
        btmoveJobDescription.setBounds(440, 180, 50, 30);
        jLayeredPane2.add(btmoveJobDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        listJobDescription.setBorder(javax.swing.BorderFactory.createTitledBorder("Job Description"));
        jScrollPane1.setViewportView(listJobDescription);

        jScrollPane1.setBounds(530, 130, 400, 130);
        jLayeredPane2.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btReceiveAccessories.setText("Receive Accessories");
        btReceiveAccessories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReceiveAccessoriesActionPerformed(evt);
            }
        });
        btReceiveAccessories.setBounds(650, 290, 180, 30);
        jLayeredPane2.add(btReceiveAccessories, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bEmployeeChargeDetail.setText("Insert Job Team");
        bEmployeeChargeDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmployeeChargeDetailActionPerformed(evt);
            }
        });
        bEmployeeChargeDetail.setBounds(500, 290, 140, 30);
        jLayeredPane2.add(bEmployeeChargeDetail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btStates1.setText("States");
        btStates1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStates1ActionPerformed(evt);
            }
        });
        btStates1.setBounds(840, 290, 110, 30);
        jLayeredPane2.add(btStates1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        chkPrintServiceOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkPrintServiceOrder.setText("Do you want print Service Order Detail ?");
        chkPrintServiceOrder.setBounds(20, 310, 300, 30);
        jLayeredPane2.add(chkPrintServiceOrder, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(50, 230, 1000, 350);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Service Order Detail"));

        lbServiceOrderID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbServiceOrderID.setText("Service Order ID");
        lbServiceOrderID.setBounds(60, 40, 110, 15);
        jLayeredPane3.add(lbServiceOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbItemDescription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbItemDescription.setText("Item Description");
        lbItemDescription.setBounds(60, 80, 120, 15);
        jLayeredPane3.add(lbItemDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbBrandName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbBrandName.setText("Brand Name");
        lbBrandName.setBounds(630, 80, 90, 15);
        jLayeredPane3.add(lbBrandName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtBrandName.setEditable(false);
        txtBrandName.setBounds(720, 80, 190, 25);
        jLayeredPane3.add(txtBrandName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtItemDescription.setEditable(false);
        txtItemDescription.setBounds(190, 80, 390, 25);
        jLayeredPane3.add(txtItemDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtServiceOrderID.setEditable(false);
        txtServiceOrderID.setBounds(190, 40, 160, 25);
        jLayeredPane3.add(txtServiceOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBounds(50, 80, 1000, 130);
        jLayeredPane1.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btaddJob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btaddJob.setText("Submit Job");
        btaddJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddJobActionPerformed(evt);
            }
        });
        btaddJob.setBounds(960, 590, 130, 40);
        jLayeredPane1.add(btaddJob, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 32)); // NOI18N
        jLabel1.setText("New Job Card");
        jLabel1.setBounds(60, 10, 250, 50);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btback.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btback.setText("Back");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });
        btback.setBounds(820, 590, 130, 40);
        jLayeredPane1.add(btback, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btmoveJobDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmoveJobDescriptionActionPerformed
        dlm.addElement(txtAddJobDescription.getText());
        listJobDescription.setModel(dlm);
        txtAddJobDescription.setText("");
        txtAddJobDescription.requestFocus();
    }//GEN-LAST:event_btmoveJobDescriptionActionPerformed

    private void btReceiveAccessoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReceiveAccessoriesActionPerformed
        //   new ReceiveAccessoriesForJob(this, true, accessoriesDetailList).setVisible(true);
    }//GEN-LAST:event_btReceiveAccessoriesActionPerformed

    private void bEmployeeChargeDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmployeeChargeDetailActionPerformed
    }//GEN-LAST:event_bEmployeeChargeDetailActionPerformed

    private void btStates1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStates1ActionPerformed
        setDateTime();
    }//GEN-LAST:event_btStates1ActionPerformed

    private void btaddJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddJobActionPerformed
        addJobDetail();
        clear();
    }//GEN-LAST:event_btaddJobActionPerformed

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        this.setVisible(false);
        pan.removeAll();
        addServiceOrder.setVisible(true);
        pan.add(addServiceOrder);
        pan.revalidate();
    }//GEN-LAST:event_btbackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEmployeeChargeDetail;
    private javax.swing.JButton btReceiveAccessories;
    private javax.swing.JButton btStates1;
    private javax.swing.JButton btaddJob;
    private javax.swing.JButton btback;
    private javax.swing.JButton btmoveJobDescription;
    private javax.swing.JCheckBox chkPrintServiceOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAddJobDescription;
    private javax.swing.JLabel lbBrandName;
    private javax.swing.JLabel lbItemDescription;
    private javax.swing.JLabel lbJobCode;
    private javax.swing.JLabel lbJobDeficiency;
    private javax.swing.JLabel lbServiceOrderID;
    private javax.swing.JList listJobDescription;
    private javax.swing.JTextField txtAddJobDescription;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtItemDescription;
    private javax.swing.JTextField txtJobCode;
    private javax.swing.JTextField txtJobDeficiency;
    private javax.swing.JTextField txtServiceOrderID;
    // End of variables declaration//GEN-END:variables

    private void viewServiceOrder() {
        customer = (Customer) orderList.get("Customer");
        serviceOrder = (ServiceOrder) orderList.get("ServiceOrder");
        item = (ServiceItem) orderList.get("ServiceItem");
        txtServiceOrderID.setText(serviceOrder.getService_Order_ID());
        txtItemDescription.setText(item.getDescription());
        txtBrandName.setText(item.getItem_Brand_Name());
        Item_Code = item.getItem_Code();
    }

    private void addJobDetail() {
        JobDetail jobDetail = new JobDetail(txtJobCode.getText(), txtJobDeficiency.getText(), 0.00, 0.00, 0.00, 0.00, setDateTime(), null, 0, Item_Code, "A");
        ArrayList<JobDescription> jobDescriptionList = new ArrayList<JobDescription>();
        JobDescription jobDescription = null;
        for (int i = 0; i < dlm.getSize(); i++) {
            jobDescription = new JobDescription(i + 1, dlm.get(i), txtJobCode.getText());
            jobDescriptionList.add(jobDescription);
        }
        try {
            int res = ServiceOrderControl.addServiceOrder(customer, serviceOrder, item);
            int res1 = JobDetailControl.addJobDetail(jobDetail);
            int res2 = JobDetailControl.addJobDecription(jobDescriptionList);
            if (res == 1) {
                JOptionPane.showMessageDialog(this, "Service Order added", "Success", JOptionPane.INFORMATION_MESSAGE);
                if (chkPrintServiceOrder.isSelected()) {
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Service Order Fail", "Fail", JOptionPane.ERROR_MESSAGE);
                }
            }
            if (res1 == 1 && res2 == 1) {
                JOptionPane.showMessageDialog(this, "Job added", "Success", JOptionPane.INFORMATION_MESSAGE);
                if (!(serviceOrderDetail == null)) {
                    serviceOrderDetail.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                    //this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Job Fail", "Fail", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddJodDetail.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddJodDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (accessoriesDetailList != null && !accessoriesDetailList.isEmpty()) {
        }
    }

    private String setDateTime() {
        SimpleDateFormat SDF = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        String Date = SDF.format(Calendar.getInstance().getTime());
        System.out.println(Date);
        return Date;
    }

    private void clear() {
        txtJobCode.setText(AutoGenerate.getNextID("JobDetail", "Job_Code", "J"));
        txtJobDeficiency.setText("");
        dlm.removeAllElements();
        listJobDescription.setModel(dlm);
    }
}
