/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import adminMain.AdminMain;
import cashier.CashierMain;
import componentControl.ThemesControl;
import dataFilesControl.ReadFile;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import model.SystemUser;
import technician.TechnicianMain;
import transparentBackground.TransferenceThisWindow;
import transparentBackground.TransparentBackground;

/**
 *
 * @author Amila
 */
public class Loading extends javax.swing.JFrame {
    AdminMain adminMain;
    CashierMain cashierMain;
    TechnicianMain technicianMain;
    SystemUser systemUser;
    int v=0;
    javax.swing.Timer t;
    //TransparentBackground transparentBackground=new TransparentBackground(this);
    /**
     * Creates new form Loading
     */
    public Loading() {
        initComponents();
        TransferenceThisWindow.tranceferantThis(this);
        setLocationRelativeTo(null);
        setBackground();
        setLoadingLabel();
        //this.add("East",transparentBackground);
        //this.add("Center",transparentBackground);
        this.setSize(185, 60);
        new AdminMain(systemUser).setVisible(true);
    }
    public Loading(final int i,final SystemUser systemUser){
        initComponents();
        TransferenceThisWindow.tranceferantThis(this);
        setLocationRelativeTo(null);
        setBackground();
        setLoadingLabel();
        //this.add("East",transparentBackground);
        //this.add("Center",transparentBackground);
        this.setSize(185, 60);
        this.systemUser=systemUser;
        t=new javax.swing.Timer(70,new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                v+=1;
                 if(v==100){
                    switch(i){
                        case 1: Loading.this.setVisible(false);
                                new AdminMain(systemUser).setVisible(true);
                                break;
                        case 2: Loading.this.setVisible(false);
                                new TechnicianMain(systemUser).setVisible(true);
                                break;
                        case 3: Loading.this.setVisible(false);
                                new CashierMain(systemUser).setVisible(true);
                                break;    
                    }
                    
                }
            }
        });
        t.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImage = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/login/109(2).gif"))); // NOI18N
        lbImage.setPreferredSize(new java.awt.Dimension(80, 53));
        getContentPane().add(lbImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 88, -1));

        lbName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbName.setText("Loading .....");
        getContentPane().add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 0, -1, 53));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Loading().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbName;
    // End of variables declaration//GEN-END:variables

    private void setBackground(){
       // ThemesControl.setTheme(this,ReadFile.getThemespathinFile());
        //setLocationRelativeTo(null);
        final String title="SUMANADASA ELECTRONIC & ELECTRICAL MANAGEMENT SYSTEM";
        setIconImage(new ImageIcon(getClass().getResource("/pictures/Neotech.png")).getImage());
        new Thread(){
            public void run(){
                boolean check=true;
                while (true) {                    
                    for (int i = 0; i < title.length()+1; i++) {
                        setTitle(title.substring(0, i));
                        try {   
                            Thread.sleep(150); 
                        } catch (Exception e) {
                        }
                    }
                    try {   
                        Thread.sleep(800); 
                    } catch (Exception e) {
                    }
                }
           }
        }.start();
    }
    
    private void setLoadingLabel(){
        new Thread(){
            public void run(){
                boolean check=true;
                while (true) {   
                    String setLabel="Loading";
                    lbName.setText(setLabel);
                    try {   
                        Thread.sleep(150); 
                    } catch (Exception e) {
                    }
                    for (int i = 0; i < 4+1; i++) {
                        setLabel+=".";
                        lbName.setText(setLabel);
                        try {   
                            Thread.sleep(300); 
                        } catch (Exception e) {
                        }
                    }
                    try {   
                        Thread.sleep(150); 
                    } catch (Exception e) {
                    }
                }
           }
        }.start();
    }
}
